<?php
/**
* @ package phpBB Extension - Tables
* @ copyright (c) 2015 Sniper_E - http://sniper-e.com
* @ license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
/**
* Tables - English Language
*
* Buttons Title_s for Selections and Guidelines
*/
		'TABLES_TITLE'				=> 'Tables',
		'TABLE_TITLE'				=> 'Table Selections',
		'TABLE_SELECTIONS_SHOW'		=> 'Show Table Selections',
		'TABLE_SELECTIONS_HIDE'		=> 'Select a Table',
		'TABLE_GUIDELINES_SHOW'		=> '<strong>Show Table Guidelines</strong>',
		'TABLE_GUIDELINES'			=> '<strong>Table Guidelines:</strong> [table=75,null] The number 75 sets the width% of a table. [table=75,tleft] The tleft floats the table left of the text. Use null, tleft, tright or tcenter. When using tcenter in the table, use [center] around the Table Title for it to line up. Max width% of table is 98%. [th=20,null], [th=30,null], [th=50,null] The numbers sets width% of each column. All [th=#% need to equal 100%. [td=null,1] The null is a class, use bg1, bg2, or any and the 1 sets the colspan of the [td]. If [td=null,2] is used you must remove one of the other [td=null,1] to make room for the 2 column. [tr=bg2] sets the class of the row. <br /><strong>Instructions:</strong> Click the Preview button after inserting your table codes in textarea. From your preview, edit all of the Title_ names and Text areas to suit your post. Adjust all the width% to balance out the look of your table, Preview and Submit.',
/**
* Selections Column Numbers
*/
		'COLUMN_ONE'			=> '1 Column',
		'COLUMN_TWO'			=> '2 Columns',
		'COLUMN_THREE'			=> '3 Columns',
		'COLUMN_FOUR'			=> '4 Columns',
		'COLUMN_FIVE'			=> '5 Columns',
		'COLUMN_SIX'			=> '6 Columns',
		'COLUMN_SEVEN'			=> '7 Columns',
/**
* Table Icon Selections Title_s on Hover
*/
		'TABLE11_TITLE'			=> 'Table - 1 Column - 1 Row',
		'TABLE12_TITLE'			=> 'Table - 1 Column - 2 Rows',
		'TABLE13_TITLE'			=> 'Table - 1 Column - 3 Rows',
		'TABLE14_TITLE'			=> 'Table - 1 Column - 4 Rows',
		'TABLE15_TITLE'			=> 'Table - 1 Column - 5 Rows',
		'TABLE16_TITLE'			=> 'Table - 1 Column - 6 Rows',
		'TABLE17_TITLE'			=> 'Table - 1 Column - 7 Rows',
		'TABLE18_TITLE'			=> 'Table - 1 Column - 8 Rows',
		'TABLE19_TITLE'			=> 'Table - 1 Column - 9 Rows',
		'TABLE110_TITLE'		=> 'Table - 1 Column - 10 Rows',
		'TABLE21_TITLE'			=> 'Table - 2 Columns - 1 Row',
		'TABLE22_TITLE'			=> 'Table - 2 Columns - 2 Rows',
		'TABLE23_TITLE'			=> 'Table - 2 Columns - 3 Rows',
		'TABLE24_TITLE'			=> 'Table - 2 Columns - 4 Rows',
		'TABLE25_TITLE'			=> 'Table - 2 Columns - 5 Rows',
		'TABLE26_TITLE'			=> 'Table - 2 Columns - 6 Rows',
		'TABLE27_TITLE'			=> 'Table - 2 Columns - 7 Rows',
		'TABLE28_TITLE'			=> 'Table - 2 Columns - 8 Rows',
		'TABLE29_TITLE'			=> 'Table - 2 Columns - 9 Rows',
		'TABLE210_TITLE'		=> 'Table - 2 Columns - 10 Rows',
		'TABLE31_TITLE'			=> 'Table - 3 Columns - 1 Row',
		'TABLE32_TITLE'			=> 'Table - 3 Columns - 2 Rows',
		'TABLE33_TITLE'			=> 'Table - 3 Columns - 3 Rows',
		'TABLE34_TITLE'			=> 'Table - 3 Columns - 4 Rows',
		'TABLE35_TITLE'			=> 'Table - 3 Columns - 5 Rows',
		'TABLE36_TITLE'			=> 'Table - 3 Columns - 6 Rows',
		'TABLE37_TITLE'			=> 'Table - 3 Columns - 7 Rows',
		'TABLE38_TITLE'			=> 'Table - 3 Columns - 8 Rows',
		'TABLE39_TITLE'			=> 'Table - 3 Columns - 9 Rows',
		'TABLE310_TITLE'		=> 'Table - 3 Columns - 10 Rows',
		'TABLE41_TITLE'			=> 'Table - 4 Columns - 1 Row',
		'TABLE42_TITLE'			=> 'Table - 4 Columns - 2 Rows',
		'TABLE43_TITLE'			=> 'Table - 4 Columns - 3 Rows',
		'TABLE44_TITLE'			=> 'Table - 4 Columns - 4 Rows',
		'TABLE45_TITLE'			=> 'Table - 4 Columns - 5 Rows',
		'TABLE46_TITLE'			=> 'Table - 4 Columns - 6 Rows',
		'TABLE47_TITLE'			=> 'Table - 4 Columns - 7 Rows',
		'TABLE48_TITLE'			=> 'Table - 4 Columns - 8 Rows',
		'TABLE49_TITLE'			=> 'Table - 4 Columns - 9 Rows',
		'TABLE410_TITLE'		=> 'Table - 4 Columns - 10 Rows',
		'TABLE51_TITLE'			=> 'Table - 5 Columns - 1 Row',
		'TABLE52_TITLE'			=> 'Table - 5 Columns - 2 Rows',
		'TABLE53_TITLE'			=> 'Table - 5 Columns - 3 Rows',
		'TABLE54_TITLE'			=> 'Table - 5 Columns - 4 Rows',
		'TABLE55_TITLE'			=> 'Table - 5 Columns - 5 Rows',
		'TABLE56_TITLE'			=> 'Table - 5 Columns - 6 Rows',
		'TABLE57_TITLE'			=> 'Table - 5 Columns - 7 Rows',
		'TABLE58_TITLE'			=> 'Table - 5 Columns - 8 Rows',
		'TABLE59_TITLE'			=> 'Table - 5 Columns - 9 Rows',
		'TABLE510_TITLE'		=> 'Table - 5 Columns - 10 Rows',
		'TABLE61_TITLE'			=> 'Table - 6 Columns - 1 Row',
		'TABLE62_TITLE'			=> 'Table - 6 Columns - 2 Rows',
		'TABLE63_TITLE'			=> 'Table - 6 Columns - 3 Rows',
		'TABLE64_TITLE'			=> 'Table - 6 Columns - 4 Rows',
		'TABLE65_TITLE'			=> 'Table - 6 Columns - 5 Rows',
		'TABLE66_TITLE'			=> 'Table - 6 Columns - 6 Rows',
		'TABLE67_TITLE'			=> 'Table - 6 Columns - 7 Rows',
		'TABLE68_TITLE'			=> 'Table - 6 Columns - 8 Rows',
		'TABLE69_TITLE'			=> 'Table - 6 Columns - 9 Rows',
		'TABLE610_TITLE'		=> 'Table - 6 Columns - 10 Rows',
		'TABLE71_TITLE'			=> 'Table - 7 Columns - 1 Row',
		'TABLE72_TITLE'			=> 'Table - 7 Columns - 2 Rows',
		'TABLE73_TITLE'			=> 'Table - 7 Columns - 3 Rows',
		'TABLE74_TITLE'			=> 'Table - 7 Columns - 4 Rows',
		'TABLE75_TITLE'			=> 'Table - 7 Columns - 5 Rows',
		'TABLE76_TITLE'			=> 'Table - 7 Columns - 6 Rows',
		'TABLE77_TITLE'			=> 'Table - 7 Columns - 7 Rows',
		'TABLE78_TITLE'			=> 'Table - 7 Columns - 8 Rows',
		'TABLE79_TITLE'			=> 'Table - 7 Columns - 9 Rows',
		'TABLE710_TITLE'		=> 'Table - 7 Columns - 10 Rows',
/**
* Tables Posted by Columns and Rows - DO NOT CHANGE
*
* Column 1
*/
		'TABLE11'	=> '[size=130]Table_Title[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE12'	=> '[size=130]Table_Title[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_2[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE13'	=> '[size=130]Table_Title[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_3[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE14'	=> '[size=130]Table_Title[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_4[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE15'	=> '[size=130]Table_Title[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_5[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE16'	=> '[size=130]Table_Title[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_6[/td]\n			[/tr]\n	[/tbody]\n[/table]',
		'TABLE17'	=> '[size=130]Table_Title[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_7[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE18'	=> '[size=130]Table_Title[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_8[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE19'	=> '[size=130]Table_Title[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_8[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_9[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE110'	=> '[size=130]Table_Title[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_8[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_9[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_10[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 2
*/
		'TABLE21'	=> '[size=130]Table_Title[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title_1[/th]\n			[th=50,null]Title_2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n			[td=null,1]Text_2[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE22'	=> '[size=130]Table_Title[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title_1[/th]\n			[th=50,null]Title_2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE23'	=> '[size=130]Table_Title[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title_1[/th]\n			[th=50,null]Title_2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE24'	=> '[size=130]Table_Title[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title_1[/th]\n			[th=50,null]Title_2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE25'	=> '[size=130]Table_Title[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title_1[/th]\n			[th=50,null]Title_2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE26'	=> '[size=130]Table_Title[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title_1[/th]\n			[th=50,null]Title_2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE27'	=> '[size=130]Table_Title[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title_1[/th]\n			[th=50,null]Title_2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE28'	=> '[size=130]Table_Title[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title_1[/th]\n			[th=50,null]Title_2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE29'	=> '[size=130]Table_Title[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title_1[/th]\n			[th=50,null]Title_2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE210'	=> '[size=130]Table_Title[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title_1[/th]\n			[th=50,null]Title_2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_110[/td]\n			[td=null,1]Text_210[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 3
*/
		'TABLE31'	=> '[size=130]Table_Title[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title_1[/th]\n			[th=33,null]Title_2[/th]\n			[th=34,null]Title_3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n			[td=null,1]Text_2[/td]\n			[td=null,1]Text_3[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE32'	=> '[size=130]Table_Title[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title_1[/th]\n			[th=33,null]Title_2[/th]\n			[th=34,null]Title_3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE33'	=> '[size=130]Table_Title[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title_1[/th]\n			[th=33,null]Title_2[/th]\n			[th=34,null]Title_3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE34'	=> '[size=130]Table_Title[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title_1[/th]\n			[th=33,null]Title_2[/th]\n			[th=34,null]Title_3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE35'	=> '[size=130]Table_Title[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title_1[/th]\n			[th=33,null]Title_2[/th]\n			[th=34,null]Title_3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE36'	=> '[size=130]Table_Title[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title_1[/th]\n			[th=33,null]Title_2[/th]\n			[th=34,null]Title_3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE37'	=> '[size=130]Table_Title[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title_1[/th]\n			[th=33,null]Title_2[/th]\n			[th=34,null]Title_3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE38'	=> '[size=130]Table_Title[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title_1[/th]\n			[th=33,null]Title_2[/th]\n			[th=34,null]Title_3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE39'	=> '[size=130]Table_Title[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title_1[/th]\n			[th=33,null]Title_2[/th]\n			[th=34,null]Title_3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n			[td=null,1]Text_39[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE310'	=> '[size=130]Table_Title[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title_1[/th]\n			[th=33,null]Title_2[/th]\n			[th=34,null]Title_3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n		[/tr]\n			[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n			[td=null,1]Text_39[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_110[/td]\n			[td=null,1]Text_210[/td]\n			[td=null,1]Text_310[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 4
*/
		'TABLE41'	=> '[size=130]Table_Title[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title_1[/th]\n			[th=25,null]Title_2[/th]\n			[th=25,null]Title_3[/th]\n			[th=25,null]Title_4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n			[td=null,1]Text_2[/td]\n			[td=null,1]Text_3[/td]\n			[td=null,1]Text_4[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE42'	=> '[size=130]Table_Title[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title_1[/th]\n			[th=25,null]Title_2[/th]\n			[th=25,null]Title_3[/th]\n			[th=25,null]Title_4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE43'	=> '[size=130]Table_Title[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title_1[/th]\n			[th=25,null]Title_2[/th]\n			[th=25,null]Title_3[/th]\n			[th=25,null]Title_4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE44'	=> '[size=130]Table_Title[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title_1[/th]\n			[th=25,null]Title_2[/th]\n			[th=25,null]Title_3[/th]\n			[th=25,null]Title_4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE45'	=> '[size=130]Table_Title[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title_1[/th]\n			[th=25,null]Title_2[/th]\n			[th=25,null]Title_3[/th]\n			[th=25,null]Title_4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE46'	=> '[size=130]Table_Title[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title_1[/th]\n			[th=25,null]Title_2[/th]\n			[th=25,null]Title_3[/th]\n			[th=25,null]Title_4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE47'	=> '[size=130]Table_Title[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title_1[/th]\n			[th=25,null]Title_2[/th]\n			[th=25,null]Title_3[/th]\n			[th=25,null]Title_4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE48'	=> '[size=130]Table_Title[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title_1[/th]\n			[th=25,null]Title_2[/th]\n			[th=25,null]Title_3[/th]\n			[th=25,null]Title_4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE49'	=> '[size=130]Table_Title[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title_1[/th]\n			[th=25,null]Title_2[/th]\n			[th=25,null]Title_3[/th]\n			[th=25,null]Title_4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n		[/tr]\n			[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n			[td=null,1]Text_39[/td]\n			[td=null,1]Text_49[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE410'	=> '[size=130]Table_Title[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title_1[/th]\n			[th=25,null]Title_2[/th]\n			[th=25,null]Title_3[/th]\n			[th=25,null]Title_4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n			[td=null,1]Text_39[/td]\n			[td=null,1]Text_49[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_110[/td]\n			[td=null,1]Text_210[/td]\n			[td=null,1]Text_310[/td]\n			[td=null,1]Text_410[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 5
*/
		'TABLE51'	=> '[size=130]Table_Title[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title_1[/th]\n			[th=20,null]Title_2[/th]\n			[th=20,null]Title_3[/th]\n			[th=20,null]Title_4[/th]\n			[th=20,null]Title_5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n			[td=null,1]Text_2[/td]\n			[td=null,1]Text_3[/td]\n			[td=null,1]Text_4[/td]\n			[td=null,1]Text_5[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE52'	=> '[size=130]Table_Title[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title_1[/th]\n			[th=20,null]Title_2[/th]\n			[th=20,null]Title_3[/th]\n			[th=20,null]Title_4[/th]\n			[th=20,null]Title_5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE53'	=> '[size=130]Table_Title[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title_1[/th]\n			[th=20,null]Title_2[/th]\n			[th=20,null]Title_3[/th]\n			[th=20,null]Title_4[/th]\n			[th=20,null]Title_5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE54'	=> '[size=130]Table_Title[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title_1[/th]\n			[th=20,null]Title_2[/th]\n			[th=20,null]Title_3[/th]\n			[th=20,null]Title_4[/th]\n			[th=20,null]Title_5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE55'	=> '[size=130]Table_Title[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title_1[/th]\n			[th=20,null]Title_2[/th]\n			[th=20,null]Title_3[/th]\n			[th=20,null]Title_4[/th]\n			[th=20,null]Title_5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE56'	=> '[size=130]Table_Title[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title_1[/th]\n			[th=20,null]Title_2[/th]\n			[th=20,null]Title_3[/th]\n			[th=20,null]Title_4[/th]\n			[th=20,null]Title_5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE57'	=> '[size=130]Table_Title[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title_1[/th]\n			[th=20,null]Title_2[/th]\n			[th=20,null]Title_3[/th]\n			[th=20,null]Title_4[/th]\n			[th=20,null]Title_5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE58'	=> '[size=130]Table_Title[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title_1[/th]\n			[th=20,null]Title_2[/th]\n			[th=20,null]Title_3[/th]\n			[th=20,null]Title_4[/th]\n			[th=20,null]Title_5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n			[td=null,1]Text_58[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE59'	=> '[size=130]Table_Title[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title_1[/th]\n			[th=20,null]Title_2[/th]\n			[th=20,null]Title_3[/th]\n			[th=20,null]Title_4[/th]\n			[th=20,null]Title_5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n			[td=null,1]Text_58[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n			[td=null,1]Text_39[/td]\n			[td=null,1]Text_49[/td]\n			[td=null,1]Text_59[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE510'	=> '[size=130]Table_Title[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title_1[/th]\n			[th=20,null]Title_2[/th]\n			[th=20,null]Title_3[/th]\n			[th=20,null]Title_4[/th]\n			[th=20,null]Title_5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n			[td=null,1]Text_58[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n			[td=null,1]Text_39[/td]\n			[td=null,1]Text_49[/td]\n			[td=null,1]Text_59[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_110[/td]\n			[td=null,1]Text_210[/td]\n			[td=null,1]Text_310[/td]\n			[td=null,1]Text_410[/td]\n			[td=null,1]Text_510[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 6
*/
		'TABLE61'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n			[td=null,1]Text_2[/td]\n			[td=null,1]Text_3[/td]\n			[td=null,1]Text_4[/td]\n			[td=null,1]Text_5[/td]\n			[td=null,1]Text_6[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE62'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE63'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE64'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE65'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE66'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n			[td=null,1]Text_66[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE67'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n			[td=null,1]Text_66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n			[td=null,1]Text_67[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE68'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n			[td=null,1]Text_66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n			[td=null,1]Text_67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n			[td=null,1]Text_58[/td]\n			[td=null,1]Text_68[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE69'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n			[td=null,1]Text_66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n			[td=null,1]Text_67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n			[td=null,1]Text_58[/td]\n			[td=null,1]Text_68[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n			[td=null,1]Text_39[/td]\n			[td=null,1]Text_49[/td]\n			[td=null,1]Text_59[/td]\n			[td=null,1]Text_69[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE610'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n			[td=null,1]Text_66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n			[td=null,1]Text_67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n			[td=null,1]Text_58[/td]\n			[td=null,1]Text_68[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n			[td=null,1]Text_39[/td]\n			[td=null,1]Text_49[/td]\n			[td=null,1]Text_59[/td]\n			[td=null,1]Text_69[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_110[/td]\n			[td=null,1]Text_210[/td]\n			[td=null,1]Text_310[/td]\n			[td=null,1]Text_410[/td]\n			[td=null,1]Text_510[/td]\n			[td=null,1]Text_610[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 7
*/
		'TABLE71'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n			[th=16,null]Title_7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_1[/td]\n			[td=null,1]Text_2[/td]\n			[td=null,1]Text_3[/td]\n			[td=null,1]Text_4[/td]\n			[td=null,1]Text_5[/td]\n			[td=null,1]Text_6[/td]\n			[td=null,1]Text_71[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE72'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n			[th=16,null]Title_7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n			[td=null,1]Text_72[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE73'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n			[th=16,null]Title_7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n			[td=null,1]Text_73[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE74'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n			[th=16,null]Title_7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n			[td=null,1]Text_74[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE75'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n			[th=16,null]Title_7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n			[td=null,1]Text_75[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE76'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n			[th=16,null]Title_7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n			[td=null,1]Text_66[/td]\n			[td=null,1]Text_7[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE77'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n			[th=16,null]Title_7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n			[td=null,1]Text_66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n			[td=null,1]Text_67[/td]\n			[td=null,1]Text_77[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE78'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n			[th=16,null]Title_7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n			[td=null,1]Text_66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n			[td=null,1]Text_67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n			[td=null,1]Text_58[/td]\n			[td=null,1]Text_68[/td]\n			[td=null,1]Text_78[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE79'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n			[th=16,null]Title_7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n			[td=null,1]Text_66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n			[td=null,1]Text_67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n			[td=null,1]Text_58[/td]\n			[td=null,1]Text_68[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n			[td=null,1]Text_39[/td]\n			[td=null,1]Text_49[/td]\n			[td=null,1]Text_59[/td]\n			[td=null,1]Text_69[/td]\n			[td=null,1]Text_79[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE710'	=> '[size=130]Table_Title[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title_1[/th]\n			[th=16,null]Title_2[/th]\n			[th=17,null]Title_3[/th]\n			[th=16,null]Title_4[/th]\n			[th=17,null]Title_5[/th]\n			[th=16,null]Title_6[/th]\n			[th=16,null]Title_7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text_11[/td]\n			[td=null,1]Text_21[/td]\n			[td=null,1]Text_31[/td]\n			[td=null,1]Text_41[/td]\n			[td=null,1]Text_51[/td]\n			[td=null,1]Text_61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_12[/td]\n			[td=null,1]Text_22[/td]\n			[td=null,1]Text_32[/td]\n			[td=null,1]Text_42[/td]\n			[td=null,1]Text_52[/td]\n			[td=null,1]Text_62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_13[/td]\n			[td=null,1]Text_23[/td]\n			[td=null,1]Text_33[/td]\n			[td=null,1]Text_43[/td]\n			[td=null,1]Text_53[/td]\n			[td=null,1]Text_63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_14[/td]\n			[td=null,1]Text_24[/td]\n			[td=null,1]Text_34[/td]\n			[td=null,1]Text_44[/td]\n			[td=null,1]Text_54[/td]\n			[td=null,1]Text_64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_15[/td]\n			[td=null,1]Text_25[/td]\n			[td=null,1]Text_35[/td]\n			[td=null,1]Text_45[/td]\n			[td=null,1]Text_55[/td]\n			[td=null,1]Text_65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_16[/td]\n			[td=null,1]Text_26[/td]\n			[td=null,1]Text_36[/td]\n			[td=null,1]Text_46[/td]\n			[td=null,1]Text_56[/td]\n			[td=null,1]Text_66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_17[/td]\n			[td=null,1]Text_27[/td]\n			[td=null,1]Text_37[/td]\n			[td=null,1]Text_47[/td]\n			[td=null,1]Text_57[/td]\n			[td=null,1]Text_67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_18[/td]\n			[td=null,1]Text_28[/td]\n			[td=null,1]Text_38[/td]\n			[td=null,1]Text_48[/td]\n			[td=null,1]Text_58[/td]\n			[td=null,1]Text_68[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text_19[/td]\n			[td=null,1]Text_29[/td]\n			[td=null,1]Text_39[/td]\n			[td=null,1]Text_49[/td]\n			[td=null,1]Text_59[/td]\n			[td=null,1]Text_69[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text_110[/td]\n			[td=null,1]Text_210[/td]\n			[td=null,1]Text_310[/td]\n			[td=null,1]Text_410[/td]\n			[td=null,1]Text_510[/td]\n			[td=null,1]Text_610[/td]\n			[td=null,1]Text_710[/td]\n		[/tr]\n	[/tbody]\n[/table]',
	)
);
