<?php
/**
* @package phpBB Extension - Tables
* @copyright (c) 2015 Sniper_E - http://sniper-e.com
* @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
*
* @Deutsch translation by Miri4ever (http://www.terra-oceanica.de)
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}


$lang = array_merge(
	$lang, array(
/**
* German language
*
* Button titles for selections and guidelines
*/
		'TABLES_TITLE'				=> 'Tabelle',
		'TABLE_TITLE'				=> 'Tabellenauswahl',
		'TABLE_SELECTIONS_SHOW'		=> 'Tabellenauswahl anzeigen',
		'TABLE_SELECTIONS_HIDE'		=> 'Wähle eine Tabelle',
		'TABLE_GUIDELINES_SHOW'		=> '<strong>Tabellenrichtlinien anzeigen</strong>',
		'TABLE_GUIDELINES_HIDE'		=> '<strong>Tabellerichtlinien ausblenden </strong>',
		'TABLE_GUIDELINES'			=> '<strong>Tabellenrichtlinien:</strong> [table=75,null] Die Zahl 75 setzt die prozentuale Breite einer Tabelle. [table=75,tleft] tleft lässt die Tabelle links vom Text fließen. Verwende null, tleft, tright oder tcenter. Wenn in der Tabelle tcenter benutzt wird, benutze auch [center] rund um den Tabellentitel zum Angleichen. Maximale prozentuale Breite der Tabelle ist 98%. [th=20,null], [th=30,null], [th=50,null] Die Zahlen setzen die prozentuale Breite für jede Spalte. Alle [th=#%] müssen gleich 100% sein. [td=null,1] null ist eine Klasse, verwende bg1, bg2, oder irgendeine andere, und die 1 setzt das Attribut colspan von [td]. Wenn [td=null,2] benutzt wird, musst du eines der anderen [td=null,1] entfernen, um Platz für die zweite Spalte zu machen. [tr=bg2] setzt die Klasse der Zeile. <br /><strong>Anweisungen:</strong> Klicke auf den Vorschau-Button, nachdem du deine Tabellencodes im Textfeld eingefügt hast. Von der Vorschau aus bearbeitest du alle Titelnamen und Textfelder, um deinen Beitrag anzupassen. Passe alle prozentualen Breiten an, um die Ansicht deiner Tabelle auszubalancieren, Vorschau und Absenden.',
/**
* Titles by column numbers
*/
		'COLUMN_ONE'			=> '1 Spalte',
		'COLUMN_TWO'			=> '2 Spalten',
		'COLUMN_THREE'			=> '3 Spalten',
		'COLUMN_FOUR'			=> '4 Spalten',
		'COLUMN_FIVE'			=> '5 Spalten',
		'COLUMN_SIX'			=> '6 Spalten',
/**
* Title on hove for table selections
*/
		'TABLE11_TITLE'			=> 'Tabelle- 1 Spalte - 1 Zeile',
		'TABLE12_TITLE'			=> 'Tabelle- 1 Spalte - 2 Zeilen',
		'TABLE13_TITLE'			=> 'Tabelle- 1 Spalte - 3 Zeilen',
		'TABLE14_TITLE'			=> 'Tabelle- 1 Spalte - 4 Zeilen',
		'TABLE15_TITLE'			=> 'Tabelle- 1 Spalte - 5 Zeilen',
		'TABLE16_TITLE'			=> 'Tabelle- 1 Spalte - 6 Zeilen',
		'TABLE17_TITLE'			=> 'Tabelle- 1 Spalte - 7 Zeilen',
		'TABLE18_TITLE'			=> 'Tabelle- 1 Spalte - 8 Zeilen',
		'TABLE19_TITLE'			=> 'Tabelle- 1 Spalte - 9 Zeilen',
		'TABLE110_TITLE'		=> 'Tabelle- 1 Spalte - 10 Zeilen',
		'TABLE21_TITLE'			=> 'Tabelle- 2 Spalten - 1 Zeile',
		'TABLE22_TITLE'			=> 'Tabelle- 2 Spalten - 2 Zeilen',
		'TABLE23_TITLE'			=> 'Tabelle- 2 Spalten - 3 Zeilen',
		'TABLE24_TITLE'			=> 'Tabelle- 2 Spalten - 4 Zeilen',
		'TABLE25_TITLE'			=> 'Tabelle- 2 Spalten - 5 Zeilen',
		'TABLE26_TITLE'			=> 'Tabelle- 2 Spalten - 6 Zeilen',
		'TABLE27_TITLE'			=> 'Tabelle- 2 Spalten - 7 Zeilen',
		'TABLE28_TITLE'			=> 'Tabelle- 2 Spalten - 8 Zeilen',
		'TABLE29_TITLE'			=> 'Tabelle- 2 Spalten - 9 Zeilen',
		'TABLE210_TITLE'		=> 'Tabelle- 2 Spalten - 10 Zeilen',
		'TABLE31_TITLE'			=> 'Tabelle- 3 Spalten - 1 Zeile',
		'TABLE32_TITLE'			=> 'Tabelle- 3 Spalten - 2 Zeilen',
		'TABLE33_TITLE'			=> 'Tabelle- 3 Spalten - 3 Zeilen',
		'TABLE34_TITLE'			=> 'Tabelle- 3 Spalten - 4 Zeilen',
		'TABLE35_TITLE'			=> 'Tabelle- 3 Spalten - 5 Zeilen',
		'TABLE36_TITLE'			=> 'Tabelle- 3 Spalten - 6 Zeilen',
		'TABLE37_TITLE'			=> 'Tabelle- 3 Spalten - 7 Zeilen',
		'TABLE38_TITLE'			=> 'Tabelle- 3 Spalten - 8 Zeilen',
		'TABLE39_TITLE'			=> 'Tabelle- 3 Spalten - 9 Zeilen',
		'TABLE310_TITLE'		=> 'Tabelle- 3 Spalten - 10 Zeilen',
		'TABLE41_TITLE'			=> 'Tabelle- 4 Spalten - 1 Zeile',
		'TABLE42_TITLE'			=> 'Tabelle- 4 Spalten - 2 Zeilen',
		'TABLE43_TITLE'			=> 'Tabelle- 4 Spalten - 3 Zeilen',
		'TABLE44_TITLE'			=> 'Tabelle- 4 Spalten - 4 Zeilen',
		'TABLE45_TITLE'			=> 'Tabelle- 4 Spalten - 5 Zeilen',
		'TABLE46_TITLE'			=> 'Tabelle- 4 Spalten - 6 Zeilen',
		'TABLE47_TITLE'			=> 'Tabelle- 4 Spalten - 7 Zeilen',
		'TABLE48_TITLE'			=> 'Tabelle- 4 Spalten - 8 Zeilen',
		'TABLE49_TITLE'			=> 'Tabelle- 4 Spalten - 9 Zeilen',
		'TABLE410_TITLE'		=> 'Tabelle- 4 Spalten - 10 Zeilen',
		'TABLE51_TITLE'			=> 'Tabelle- 5 Spalten - 1 Zeile',
		'TABLE52_TITLE'			=> 'Tabelle- 5 Spalten - 2 Zeilen',
		'TABLE53_TITLE'			=> 'Tabelle- 5 Spalten - 3 Zeilen',
		'TABLE54_TITLE'			=> 'Tabelle- 5 Spalten - 4 Zeilen',
		'TABLE55_TITLE'			=> 'Tabelle- 5 Spalten - 5 Zeilen',
		'TABLE56_TITLE'			=> 'Tabelle- 5 Spalten - 6 Zeilen',
		'TABLE57_TITLE'			=> 'Tabelle- 5 Spalten - 7 Zeilen',
		'TABLE58_TITLE'			=> 'Tabelle- 5 Spalten - 8 Zeilen',
		'TABLE59_TITLE'			=> 'Tabelle- 5 Spalten - 9 Zeilen',
		'TABLE510_TITLE'		=> 'Tabelle- 5 Spalten - 10 Zeilen',
		'TABLE61_TITLE'			=> 'Tabelle- 6 Spalten - 1 Zeile',
		'TABLE62_TITLE'			=> 'Tabelle- 6 Spalten - 2 Zeilen',
		'TABLE63_TITLE'			=> 'Tabelle- 6 Spalten - 3 Zeilen',
		'TABLE64_TITLE'			=> 'Tabelle- 6 Spalten - 4 Zeilen',
		'TABLE65_TITLE'			=> 'Tabelle- 6 Spalten - 5 Zeilen',
		'TABLE66_TITLE'			=> 'Tabelle- 6 Spalten - 6 Zeilen',
		'TABLE67_TITLE'			=> 'Tabelle- 6 Spalten - 7 Zeilen',
		'TABLE68_TITLE'			=> 'Tabelle- 6 Spalten - 8 Zeilen',
		'TABLE69_TITLE'			=> 'Tabelle- 6 Spalten - 9 Zeilen',
		'TABLE610_TITLE'		=> 'Tabelle- 6 Spalten - 10 Zeilen',
/**
* Generated tables posted by columns and rows
*
* Column 1
*/
		'TABLE11'	=> '[size=130]Tabellentitel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE12'	=> '[size=130]Tabellentitel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text2[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE13'	=> '[size=130]Tabellentitel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text3[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE14'	=> '[size=130]Tabellentitel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text4[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE15'	=> '[size=130]Tabellentitel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text5[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE16'	=> '[size=130]Tabellentitel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text6[/td]\n			[/tr]\n	[/tbody]\n[/table]',
		'TABLE17'	=> '[size=130]Tabellentitel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text7[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE18'	=> '[size=130]Tabellentitel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text8[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE19'	=> '[size=130]Tabellentitel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text8[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text9[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE110'	=> '[size=130]Tabellentitel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Title[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text8[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text9[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text10[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 2
*/
		'TABLE21'	=> '[size=130]Tabellentitel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title1[/th]\n			[th=50,null]Title2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n			[td=null,1]Text2[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE22'	=> '[size=130]Tabellentitel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title1[/th]\n			[th=50,null]Title2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE23'	=> '[size=130]Tabellentitel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title1[/th]\n			[th=50,null]Title2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE24'	=> '[size=130]Tabellentitel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title1[/th]\n			[th=50,null]Title2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE25'	=> '[size=130]Tabellentitel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title1[/th]\n			[th=50,null]Title2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE26'	=> '[size=130]Tabellentitel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title1[/th]\n			[th=50,null]Title2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE27'	=> '[size=130]Tabellentitel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title1[/th]\n			[th=50,null]Title2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE28'	=> '[size=130]Tabellentitel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title1[/th]\n			[th=50,null]Title2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE29'	=> '[size=130]Tabellentitel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title1[/th]\n			[th=50,null]Title2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE210'	=> '[size=130]Tabellentitel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Title1[/th]\n			[th=50,null]Title2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text110[/td]\n			[td=null,1]Text210[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 3
*/
		'TABLE31'	=> '[size=130]Tabellentitel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title1[/th]\n			[th=33,null]Title2[/th]\n			[th=34,null]Title3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n			[td=null,1]Text2[/td]\n			[td=null,1]Text3[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE32'	=> '[size=130]Tabellentitel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title1[/th]\n			[th=33,null]Title2[/th]\n			[th=34,null]Title3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE33'	=> '[size=130]Tabellentitel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title1[/th]\n			[th=33,null]Title2[/th]\n			[th=34,null]Title3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE34'	=> '[size=130]Tabellentitel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title1[/th]\n			[th=33,null]Title2[/th]\n			[th=34,null]Title3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE35'	=> '[size=130]Tabellentitel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title1[/th]\n			[th=33,null]Title2[/th]\n			[th=34,null]Title3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE36'	=> '[size=130]Tabellentitel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title1[/th]\n			[th=33,null]Title2[/th]\n			[th=34,null]Title3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE37'	=> '[size=130]Tabellentitel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title1[/th]\n			[th=33,null]Title2[/th]\n			[th=34,null]Title3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE38'	=> '[size=130]Tabellentitel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title1[/th]\n			[th=33,null]Title2[/th]\n			[th=34,null]Title3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE39'	=> '[size=130]Tabellentitel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title1[/th]\n			[th=33,null]Title2[/th]\n			[th=34,null]Title3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n			[td=null,1]Text39[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE310'	=> '[size=130]Tabellentitel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Title1[/th]\n			[th=33,null]Title2[/th]\n			[th=34,null]Title3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n		[/tr]\n			[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n			[td=null,1]Text39[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text110[/td]\n			[td=null,1]Text210[/td]\n			[td=null,1]Text310[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 4
*/
		'TABLE41'	=> '[size=130]Tabellentitel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title1[/th]\n			[th=25,null]Title2[/th]\n			[th=25,null]Title3[/th]\n			[th=25,null]Title4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n			[td=null,1]Text2[/td]\n			[td=null,1]Text3[/td]\n			[td=null,1]Text4[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE42'	=> '[size=130]Tabellentitel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title1[/th]\n			[th=25,null]Title2[/th]\n			[th=25,null]Title3[/th]\n			[th=25,null]Title4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE43'	=> '[size=130]Tabellentitel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title1[/th]\n			[th=25,null]Title2[/th]\n			[th=25,null]Title3[/th]\n			[th=25,null]Title4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE44'	=> '[size=130]Tabellentitel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title1[/th]\n			[th=25,null]Title2[/th]\n			[th=25,null]Title3[/th]\n			[th=25,null]Title4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE45'	=> '[size=130]Tabellentitel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title1[/th]\n			[th=25,null]Title2[/th]\n			[th=25,null]Title3[/th]\n			[th=25,null]Title4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE46'	=> '[size=130]Tabellentitel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title1[/th]\n			[th=25,null]Title2[/th]\n			[th=25,null]Title3[/th]\n			[th=25,null]Title4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE47'	=> '[size=130]Tabellentitel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title1[/th]\n			[th=25,null]Title2[/th]\n			[th=25,null]Title3[/th]\n			[th=25,null]Title4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE48'	=> '[size=130]Tabellentitel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title1[/th]\n			[th=25,null]Title2[/th]\n			[th=25,null]Title3[/th]\n			[th=25,null]Title4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE49'	=> '[size=130]Tabellentitel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title1[/th]\n			[th=25,null]Title2[/th]\n			[th=25,null]Title3[/th]\n			[th=25,null]Title4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n		[/tr]\n			[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n			[td=null,1]Text39[/td]\n			[td=null,1]Text49[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE410'	=> '[size=130]Tabellentitel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Title1[/th]\n			[th=25,null]Title2[/th]\n			[th=25,null]Title3[/th]\n			[th=25,null]Title4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n			[td=null,1]Text39[/td]\n			[td=null,1]Text49[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text110[/td]\n			[td=null,1]Text210[/td]\n			[td=null,1]Text310[/td]\n			[td=null,1]Text410[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 5
*/
		'TABLE51'	=> '[size=130]Tabellentitel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title1[/th]\n			[th=20,null]Title2[/th]\n			[th=20,null]Title3[/th]\n			[th=20,null]Title4[/th]\n			[th=20,null]Title5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n			[td=null,1]Text2[/td]\n			[td=null,1]Text3[/td]\n			[td=null,1]Text4[/td]\n			[td=null,1]Text5[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE52'	=> '[size=130]Tabellentitel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title1[/th]\n			[th=20,null]Title2[/th]\n			[th=20,null]Title3[/th]\n			[th=20,null]Title4[/th]\n			[th=20,null]Title5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE53'	=> '[size=130]Tabellentitel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title1[/th]\n			[th=20,null]Title2[/th]\n			[th=20,null]Title3[/th]\n			[th=20,null]Title4[/th]\n			[th=20,null]Title5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE54'	=> '[size=130]Tabellentitel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title1[/th]\n			[th=20,null]Title2[/th]\n			[th=20,null]Title3[/th]\n			[th=20,null]Title4[/th]\n			[th=20,null]Title5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE55'	=> '[size=130]Tabellentitel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title1[/th]\n			[th=20,null]Title2[/th]\n			[th=20,null]Title3[/th]\n			[th=20,null]Title4[/th]\n			[th=20,null]Title5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE56'	=> '[size=130]Tabellentitel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title1[/th]\n			[th=20,null]Title2[/th]\n			[th=20,null]Title3[/th]\n			[th=20,null]Title4[/th]\n			[th=20,null]Title5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE57'	=> '[size=130]Tabellentitel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title1[/th]\n			[th=20,null]Title2[/th]\n			[th=20,null]Title3[/th]\n			[th=20,null]Title4[/th]\n			[th=20,null]Title5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE58'	=> '[size=130]Tabellentitel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title1[/th]\n			[th=20,null]Title2[/th]\n			[th=20,null]Title3[/th]\n			[th=20,null]Title4[/th]\n			[th=20,null]Title5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n			[td=null,1]Text58[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE59'	=> '[size=130]Tabellentitel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title1[/th]\n			[th=20,null]Title2[/th]\n			[th=20,null]Title3[/th]\n			[th=20,null]Title4[/th]\n			[th=20,null]Title5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n			[td=null,1]Text58[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n			[td=null,1]Text39[/td]\n			[td=null,1]Text49[/td]\n			[td=null,1]Text59[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE510'	=> '[size=130]Tabellentitel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Title1[/th]\n			[th=20,null]Title2[/th]\n			[th=20,null]Title3[/th]\n			[th=20,null]Title4[/th]\n			[th=20,null]Title5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n			[td=null,1]Text58[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n			[td=null,1]Text39[/td]\n			[td=null,1]Text49[/td]\n			[td=null,1]Text59[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text110[/td]\n			[td=null,1]Text210[/td]\n			[td=null,1]Text310[/td]\n			[td=null,1]Text410[/td]\n			[td=null,1]Text510[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 6
*/
		'TABLE61'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title1[/th]\n			[th=16,null]Title2[/th]\n			[th=17,null]Title3[/th]\n			[th=16,null]Title4[/th]\n			[th=17,null]Title5[/th]\n			[th=16,null]Title6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n			[td=null,1]Text2[/td]\n			[td=null,1]Text3[/td]\n			[td=null,1]Text4[/td]\n			[td=null,1]Text5[/td]\n			[td=null,1]Text6[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE62'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title1[/th]\n			[th=16,null]Title2[/th]\n			[th=17,null]Title3[/th]\n			[th=16,null]Title4[/th]\n			[th=17,null]Title5[/th]\n			[th=16,null]Title6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE63'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title1[/th]\n			[th=16,null]Title2[/th]\n			[th=17,null]Title3[/th]\n			[th=16,null]Title4[/th]\n			[th=17,null]Title5[/th]\n			[th=16,null]Title6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE64'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title1[/th]\n			[th=16,null]Title2[/th]\n			[th=17,null]Title3[/th]\n			[th=16,null]Title4[/th]\n			[th=17,null]Title5[/th]\n			[th=16,null]Title6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE65'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title1[/th]\n			[th=16,null]Title2[/th]\n			[th=17,null]Title3[/th]\n			[th=16,null]Title4[/th]\n			[th=17,null]Title5[/th]\n			[th=16,null]Title6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE66'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title1[/th]\n			[th=16,null]Title2[/th]\n			[th=17,null]Title3[/th]\n			[th=16,null]Title4[/th]\n			[th=17,null]Title5[/th]\n			[th=16,null]Title6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n			[td=null,1]Text66[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE67'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title1[/th]\n			[th=16,null]Title2[/th]\n			[th=17,null]Title3[/th]\n			[th=16,null]Title4[/th]\n			[th=17,null]Title5[/th]\n			[th=16,null]Title6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n			[td=null,1]Text66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n			[td=null,1]Text67[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE68'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title1[/th]\n			[th=16,null]Title2[/th]\n			[th=17,null]Title3[/th]\n			[th=16,null]Title4[/th]\n			[th=17,null]Title5[/th]\n			[th=16,null]Title6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n			[td=null,1]Text66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n			[td=null,1]Text67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n			[td=null,1]Text58[/td]\n			[td=null,1]Text68[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE69'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title1[/th]\n			[th=16,null]Title2[/th]\n			[th=17,null]Title3[/th]\n			[th=16,null]Title4[/th]\n			[th=17,null]Title5[/th]\n			[th=16,null]Title6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n			[td=null,1]Text66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n			[td=null,1]Text67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n			[td=null,1]Text58[/td]\n			[td=null,1]Text68[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n			[td=null,1]Text39[/td]\n			[td=null,1]Text49[/td]\n			[td=null,1]Text59[/td]\n			[td=null,1]Text69[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE610'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Title1[/th]\n			[th=16,null]Title2[/th]\n			[th=17,null]Title3[/th]\n			[th=16,null]Title4[/th]\n			[th=17,null]Title5[/th]\n			[th=16,null]Title6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n			[td=null,1]Text66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n			[td=null,1]Text67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n			[td=null,1]Text58[/td]\n			[td=null,1]Text68[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n			[td=null,1]Text39[/td]\n			[td=null,1]Text49[/td]\n			[td=null,1]Text59[/td]\n			[td=null,1]Text69[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text110[/td]\n			[td=null,1]Text210[/td]\n			[td=null,1]Text310[/td]\n			[td=null,1]Text410[/td]\n			[td=null,1]Text510[/td]\n			[td=null,1]Text610[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 7
*/
		'TABLE71'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Title1[/th]\n			[th=14,null]Title2[/th]\n			[th=14,null]Title3[/th]\n			[th=14,null]Title4[/th]\n			[th=14,null]Title5[/th]\n			[th=14,null]Title6[/th]\n			[th=16,null]Title7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text1[/td]\n			[td=null,1]Text2[/td]\n			[td=null,1]Text3[/td]\n			[td=null,1]Text4[/td]\n			[td=null,1]Text5[/td]\n			[td=null,1]Text6[/td]\n			[td=null,1]Text71[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE72'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Title1[/th]\n			[th=14,null]Title2[/th]\n			[th=14,null]Title3[/th]\n			[th=14,null]Title4[/th]\n			[th=14,null]Title5[/th]\n			[th=14,null]Title6[/th]\n			[th=16,null]Title7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n			[td=null,1]Text71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n			[td=null,1]Text72[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE73'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Title1[/th]\n			[th=14,null]Title2[/th]\n			[th=14,null]Title3[/th]\n			[th=14,null]Title4[/th]\n			[th=14,null]Title5[/th]\n			[th=14,null]Title6[/th]\n			[th=16,null]Title7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n			[td=null,1]Text71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n			[td=null,1]Text72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n			[td=null,1]Text73[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE74'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Title1[/th]\n			[th=14,null]Title2[/th]\n			[th=14,null]Title3[/th]\n			[th=14,null]Title4[/th]\n			[th=14,null]Title5[/th]\n			[th=14,null]Title6[/th]\n			[th=16,null]Title7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n			[td=null,1]Text71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n			[td=null,1]Text72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n			[td=null,1]Text73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n			[td=null,1]Text74[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE75'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Title1[/th]\n			[th=14,null]Title2[/th]\n			[th=14,null]Title3[/th]\n			[th=14,null]Title4[/th]\n			[th=14,null]Title5[/th]\n			[th=14,null]Title6[/th]\n			[th=16,null]Title7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n			[td=null,1]Text71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n			[td=null,1]Text72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n			[td=null,1]Text73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n			[td=null,1]Text74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n			[td=null,1]Text75[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE76'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Title1[/th]\n			[th=14,null]Title2[/th]\n			[th=14,null]Title3[/th]\n			[th=14,null]Title4[/th]\n			[th=14,null]Title5[/th]\n			[th=14,null]Title6[/th]\n			[th=16,null]Title7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n			[td=null,1]Text71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n			[td=null,1]Text72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n			[td=null,1]Text73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n			[td=null,1]Text74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n			[td=null,1]Text75[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n			[td=null,1]Text66[/td]\n			[td=null,1]Text76[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE77'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Title1[/th]\n			[th=14,null]Title2[/th]\n			[th=14,null]Title3[/th]\n			[th=14,null]Title4[/th]\n			[th=14,null]Title5[/th]\n			[th=14,null]Title6[/th]\n			[th=16,null]Title7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n			[td=null,1]Text71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n			[td=null,1]Text72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n			[td=null,1]Text73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n			[td=null,1]Text74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n			[td=null,1]Text75[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n			[td=null,1]Text66[/td]\n			[td=null,1]Text76[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n			[td=null,1]Text67[/td]\n			[td=null,1]Text77[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE78'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Title1[/th]\n			[th=14,null]Title2[/th]\n			[th=14,null]Title3[/th]\n			[th=14,null]Title4[/th]\n			[th=14,null]Title5[/th]\n			[th=14,null]Title6[/th]\n			[th=16,null]Title7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n			[td=null,1]Text71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n			[td=null,1]Text72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n			[td=null,1]Text73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n			[td=null,1]Text74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n			[td=null,1]Text75[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n			[td=null,1]Text66[/td]\n			[td=null,1]Text76[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n			[td=null,1]Text67[/td]\n			[td=null,1]Text77[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n			[td=null,1]Text58[/td]\n			[td=null,1]Text68[/td]\n			[td=null,1]Text78[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE79'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Title1[/th]\n			[th=14,null]Title2[/th]\n			[th=14,null]Title3[/th]\n			[th=14,null]Title4[/th]\n			[th=14,null]Title5[/th]\n			[th=14,null]Title6[/th]\n			[th=16,null]Title7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n			[td=null,1]Text71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n			[td=null,1]Text72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n			[td=null,1]Text73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n			[td=null,1]Text74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n			[td=null,1]Text75[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n			[td=null,1]Text66[/td]\n			[td=null,1]Text76[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n			[td=null,1]Text67[/td]\n			[td=null,1]Text77[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n			[td=null,1]Text58[/td]\n			[td=null,1]Text68[/td]\n			[td=null,1]Text78[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n			[td=null,1]Text39[/td]\n			[td=null,1]Text49[/td]\n			[td=null,1]Text59[/td]\n			[td=null,1]Text69[/td]\n			[td=null,1]Text79[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE710'	=> '[size=130]Tabellentitel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Title1[/th]\n			[th=14,null]Title2[/th]\n			[th=14,null]Title3[/th]\n			[th=14,null]Title4[/th]\n			[th=14,null]Title5[/th]\n			[th=14,null]Title6[/th]\n			[th=16,null]Title7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Text11[/td]\n			[td=null,1]Text21[/td]\n			[td=null,1]Text31[/td]\n			[td=null,1]Text41[/td]\n			[td=null,1]Text51[/td]\n			[td=null,1]Text61[/td]\n			[td=null,1]Text71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text12[/td]\n			[td=null,1]Text22[/td]\n			[td=null,1]Text32[/td]\n			[td=null,1]Text42[/td]\n			[td=null,1]Text52[/td]\n			[td=null,1]Text62[/td]\n			[td=null,1]Text72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text13[/td]\n			[td=null,1]Text23[/td]\n			[td=null,1]Text33[/td]\n			[td=null,1]Text43[/td]\n			[td=null,1]Text53[/td]\n			[td=null,1]Text63[/td]\n			[td=null,1]Text73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text14[/td]\n			[td=null,1]Text24[/td]\n			[td=null,1]Text34[/td]\n			[td=null,1]Text44[/td]\n			[td=null,1]Text54[/td]\n			[td=null,1]Text64[/td]\n			[td=null,1]Text74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text15[/td]\n			[td=null,1]Text25[/td]\n			[td=null,1]Text35[/td]\n			[td=null,1]Text45[/td]\n			[td=null,1]Text55[/td]\n			[td=null,1]Text65[/td]\n			[td=null,1]Text75[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text16[/td]\n			[td=null,1]Text26[/td]\n			[td=null,1]Text36[/td]\n			[td=null,1]Text46[/td]\n			[td=null,1]Text56[/td]\n			[td=null,1]Text66[/td]\n			[td=null,1]Text76[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text17[/td]\n			[td=null,1]Text27[/td]\n			[td=null,1]Text37[/td]\n			[td=null,1]Text47[/td]\n			[td=null,1]Text57[/td]\n			[td=null,1]Text67[/td]\n			[td=null,1]Text77[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text18[/td]\n			[td=null,1]Text28[/td]\n			[td=null,1]Text38[/td]\n			[td=null,1]Text48[/td]\n			[td=null,1]Text58[/td]\n			[td=null,1]Text68[/td]\n			[td=null,1]Text78[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Text19[/td]\n			[td=null,1]Text29[/td]\n			[td=null,1]Text39[/td]\n			[td=null,1]Text49[/td]\n			[td=null,1]Text59[/td]\n			[td=null,1]Text69[/td]\n			[td=null,1]Text79[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Text110[/td]\n			[td=null,1]Text210[/td]\n			[td=null,1]Text310[/td]\n			[td=null,1]Text410[/td]\n			[td=null,1]Text510[/td]\n			[td=null,1]Text610[/td]\n			[td=null,1]Text710[/td]\n		[/tr]\n	[/tbody]\n[/table]',
	)
);
