<?php
/**
* @package phpBB Extension - Tables
* @copyright (c) 2015 Sniper_E - http://sniper-e.com
* Nederlandse vertaling @ Solidjeuh <https://www.froddelpower.be>
* @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
*
* @Dutch translation by Solidjeuh (https://www.froddelpower.be)
* Nederlandse vertaling @ Solidjeuh
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
/**
* English language
*
* Button titles for selections and guidelines
*/
		'TABLES_TITLE'				=> 'Tabellen',
		'TABLE_TITLE'				=> 'Tabellen selecties',
		'TABLE_SELECTIONS_SHOW'		=> 'Toon tabellen selecties',
		'TABLE_SELECTIONS_HIDE'		=> 'Verberg tabellen selecties',
		'TABLE_GUIDELINES_SHOW'		=> '<strong>Toon tabellen handleiding</strong>',
		'TABLE_GUIDELINES_HIDE'		=> '<strong>Verberg tabellen handleiding</strong>',
		'TABLE_GUIDELINES'			=> '<strong>Tabellen handleiding: </strong> [table=75,null] Het getal 75 stelt het breedte % van een tabel in. Max breedte % van een tabel is is <strong>98%</strong>. [table=75,tleft] De tleft code laat de tabel links van de tekst zweven. Gebruik null, tleft, tright of tcenter op een tabel. Wanneer tcenter gebruikt wordt in de tabel, gebruik dan [center] rondom de Tabel Titel om alles mooi uit te lijnen. Gebruik [tr=textcenter] of [td=textcenter,1] om de tekst te centreren in de tabel. Gebruik textleft, textcenter of textright om de tekst uit te lijnen. [th=20,null], [th=30,null], [th=50,null] De getallen stellen het breedte % in van iedere kolom. Alle [th=#% moeten samen 100% uitkomen. [tr=bg2] Stelt de klasse van de rij in. [td=null,1] De null is een lege klasse, gebruik bg1, bg2, of iedere andere klasse. De 1 stelt het aantal cellen van de [td] in. Indien [td=null,2] gebruikt wordt moet je 1 van de andere [td=null,1] verwijderen om plaats te maken voor de 2 kolom.<br /><strong>Instructies: </strong> Klik op de voorbeeld knop nadat u uw tabel codes in het tekstveld hebt ingevoegd. In je voorbeeld kan je alle titel namen en tekst gebieden aanpassen naar eigen keuze. Pas alle % getallen aan om uw tabel in evenwicht te brengen, voorbeeld tonen en verzenden.',
/**
* Titles by column numbers
*/
		'COLUMN_ONE'			=> '1 kolom',
		'COLUMN_TWO'			=> '2 kolommen',
		'COLUMN_THREE'			=> '3 kolommen',
		'COLUMN_FOUR'			=> '4 kolommen',
		'COLUMN_FIVE'			=> '5 kolommen',
		'COLUMN_SIX'			=> '6 kolommen',
		'COLUMN_SEVEN'			=> '7 kolommen',
/**
* Title on hove for table selections
*/
		'TABLE11_TITLE'			=> 'Tabel - 1 kolom, 1 rij',
		'TABLE12_TITLE'			=> 'Tabel - 1 kolom, 2 rijen',
		'TABLE13_TITLE'			=> 'Tabel - 1 kolom, 3 rijen',
		'TABLE14_TITLE'			=> 'Tabel - 1 kolom, 4 rijen',
		'TABLE15_TITLE'			=> 'Tabel - 1 kolom, 5 rijen',
		'TABLE16_TITLE'			=> 'Tabel - 1 kolom, 6 rijen',
		'TABLE17_TITLE'			=> 'Tabel - 1 kolom, 7 rijen',
		'TABLE18_TITLE'			=> 'Tabel - 1 kolom, 8 rijen',
		'TABLE19_TITLE'			=> 'Tabel - 1 kolom, 9 rijen',
		'TABLE110_TITLE'		=> 'Tabel - 1 kolom, 10 rijen',
		'TABLE21_TITLE'			=> 'Tabel - 2 kolommen, 1 rij',
		'TABLE22_TITLE'			=> 'Tabel - 2 kolommen, 2 rijen',
		'TABLE23_TITLE'			=> 'Tabel - 2 kolommen, 3 rijen',
		'TABLE24_TITLE'			=> 'Tabel - 2 kolommen, 4 rijen',
		'TABLE25_TITLE'			=> 'Tabel - 2 kolommen, 5 rijen',
		'TABLE26_TITLE'			=> 'Tabel - 2 kolommen, 6 rijen',
		'TABLE27_TITLE'			=> 'Tabel - 2 kolommen, 7 rijen',
		'TABLE28_TITLE'			=> 'Tabel - 2 kolommen, 8 rijen',
		'TABLE29_TITLE'			=> 'Tabel - 2 kolommen, 9 rijen',
		'TABLE210_TITLE'		=> 'Tabel - 2 kolommen, 10 rijen',
		'TABLE31_TITLE'			=> 'Tabel - 3 kolommen, 1 rij',
		'TABLE32_TITLE'			=> 'Tabel - 3 kolommen, 2 rijen',
		'TABLE33_TITLE'			=> 'Tabel - 3 kolommen, 3 rijen',
		'TABLE34_TITLE'			=> 'Tabel - 3 kolommen, 4 rijen',
		'TABLE35_TITLE'			=> 'Tabel - 3 kolommen, 5 rijen',
		'TABLE36_TITLE'			=> 'Tabel - 3 kolommen, 6 rijen',
		'TABLE37_TITLE'			=> 'Tabel - 3 kolommen, 7 rijen',
		'TABLE38_TITLE'			=> 'Tabel - 3 kolommen, 8 rijen',
		'TABLE39_TITLE'			=> 'Tabel - 3 kolommen, 9 rijen',
		'TABLE310_TITLE'		=> 'Tabel - 3 kolommen, 10 rijen',
		'TABLE41_TITLE'			=> 'Tabel - 4 kolommen, 1 rij',
		'TABLE42_TITLE'			=> 'Tabel - 4 kolommen, 2 rijen',
		'TABLE43_TITLE'			=> 'Tabel - 4 kolommen, 3 rijen',
		'TABLE44_TITLE'			=> 'Tabel - 4 kolommen, 4 rijen',
		'TABLE45_TITLE'			=> 'Tabel - 4 kolommen, 5 rijen',
		'TABLE46_TITLE'			=> 'Tabel - 4 kolommen, 6 rijen',
		'TABLE47_TITLE'			=> 'Tabel - 4 kolommen, 7 rijen',
		'TABLE48_TITLE'			=> 'Tabel - 4 kolommen, 8 rijen',
		'TABLE49_TITLE'			=> 'Tabel - 4 kolommen, 9 rijen',
		'TABLE410_TITLE'		=> 'Tabel - 4 kolommen, 10 rijen',
		'TABLE51_TITLE'			=> 'Tabel - 5 kolommen, 1 rij',
		'TABLE52_TITLE'			=> 'Tabel - 5 kolommen, 2 rijen',
		'TABLE53_TITLE'			=> 'Tabel - 5 kolommen, 3 rijen',
		'TABLE54_TITLE'			=> 'Tabel - 5 kolommen, 4 rijen',
		'TABLE55_TITLE'			=> 'Tabel - 5 kolommen, 5 rijen',
		'TABLE56_TITLE'			=> 'Tabel - 5 kolommen, 6 rijen',
		'TABLE57_TITLE'			=> 'Tabel - 5 kolommen, 7 rijen',
		'TABLE58_TITLE'			=> 'Tabel - 5 kolommen, 8 rijen',
		'TABLE59_TITLE'			=> 'Tabel - 5 kolommen, 9 rijen',
		'TABLE510_TITLE'		=> 'Tabel - 5 kolommen, 10 rijen',
		'TABLE61_TITLE'			=> 'Tabel - 6 kolommen, 1 rij',
		'TABLE62_TITLE'			=> 'Tabel - 6 kolommen, 2 rijen',
		'TABLE63_TITLE'			=> 'Tabel - 6 kolommen, 3 rijen',
		'TABLE64_TITLE'			=> 'Tabel - 6 kolommen, 4 rijen',
		'TABLE65_TITLE'			=> 'Tabel - 6 kolommen, 5 rijen',
		'TABLE66_TITLE'			=> 'Tabel - 6 kolommen, 6 rijen',
		'TABLE67_TITLE'			=> 'Tabel - 6 kolommen, 7 rijen',
		'TABLE68_TITLE'			=> 'Tabel - 6 kolommen, 8 rijen',
		'TABLE69_TITLE'			=> 'Tabel - 6 kolommen, 9 rijen',
		'TABLE610_TITLE'		=> 'Tabel - 6 kolommen, 10 rijen',
		'TABLE71_TITLE'			=> 'Tabel - 7 kolommen, 1 rij',
		'TABLE72_TITLE'			=> 'Tabel - 7 kolommen, 2 rijen',
		'TABLE73_TITLE'			=> 'Tabel - 7 kolommen, 3 rijen',
		'TABLE74_TITLE'			=> 'Tabel - 7 kolommen, 4 rijen',
		'TABLE75_TITLE'			=> 'Tabel - 7 kolommen, 5 rijen',
		'TABLE76_TITLE'			=> 'Tabel - 7 kolommen, 6 rijen',
		'TABLE77_TITLE'			=> 'Tabel - 7 kolommen, 7 rijen',
		'TABLE78_TITLE'			=> 'Tabel - 7 kolommen, 8 rijen',
		'TABLE79_TITLE'			=> 'Tabel - 7 kolommen, 9 rijen',
		'TABLE710_TITLE'		=> 'Tabel - 7 kolommen, 10 rijen',
/**
* Generated tables posted by columns and rows
*
* Column 1
*/
		'TABLE11'	=> '[size=130]Tabel Titel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titel[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE12'	=> '[size=130]Tabel Titel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titel[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst2[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE13'	=> '[size=130]Tabel Titel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titel[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst3[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE14'	=> '[size=130]Tabel Titel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titel[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst4[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE15'	=> '[size=130]Tabel Titel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titel[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst5[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE16'	=> '[size=130]Tabel Titel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titel[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst6[/td]\n			[/tr]\n	[/tbody]\n[/table]',
		'TABLE17'	=> '[size=130]Tabel Titel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titel[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst7[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE18'	=> '[size=130]Tabel Titel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titel[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst8[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE19'	=> '[size=130]Tabel Titel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titel[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst8[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst9[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE110'	=> '[size=130]Tabel Titel[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titel[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst8[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst9[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst10[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 2
*/
		'TABLE21'	=> '[size=130]Tabel Titel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titel1[/th]\n			[th=50,null]Titel2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n			[td=null,1]Tekst2[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE22'	=> '[size=130]Tabel Titel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titel1[/th]\n			[th=50,null]Titel2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE23'	=> '[size=130]Tabel Titel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titel1[/th]\n			[th=50,null]Titel2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE24'	=> '[size=130]Tabel Titel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titel1[/th]\n			[th=50,null]Titel2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE25'	=> '[size=130]Tabel Titel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titel1[/th]\n			[th=50,null]Titel2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE26'	=> '[size=130]Tabel Titel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titel1[/th]\n			[th=50,null]Titel2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE27'	=> '[size=130]Tabel Titel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titel1[/th]\n			[th=50,null]Titel2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE28'	=> '[size=130]Tabel Titel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titel1[/th]\n			[th=50,null]Titel2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE29'	=> '[size=130]Tabel Titel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titel1[/th]\n			[th=50,null]Titel2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE210'	=> '[size=130]Tabel Titel[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titel1[/th]\n			[th=50,null]Titel2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst110[/td]\n			[td=null,1]Tekst210[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 3
*/
		'TABLE31'	=> '[size=130]Tabel Titel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titel1[/th]\n			[th=33,null]Titel2[/th]\n			[th=34,null]Titel3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n			[td=null,1]Tekst2[/td]\n			[td=null,1]Tekst3[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE32'	=> '[size=130]Tabel Titel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titel1[/th]\n			[th=33,null]Titel2[/th]\n			[th=34,null]Titel3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE33'	=> '[size=130]Tabel Titel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titel1[/th]\n			[th=33,null]Titel2[/th]\n			[th=34,null]Titel3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE34'	=> '[size=130]Tabel Titel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titel1[/th]\n			[th=33,null]Titel2[/th]\n			[th=34,null]Titel3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE35'	=> '[size=130]Tabel Titel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titel1[/th]\n			[th=33,null]Titel2[/th]\n			[th=34,null]Titel3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE36'	=> '[size=130]Tabel Titel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titel1[/th]\n			[th=33,null]Titel2[/th]\n			[th=34,null]Titel3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE37'	=> '[size=130]Tabel Titel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titel1[/th]\n			[th=33,null]Titel2[/th]\n			[th=34,null]Titel3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE38'	=> '[size=130]Tabel Titel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titel1[/th]\n			[th=33,null]Titel2[/th]\n			[th=34,null]Titel3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE39'	=> '[size=130]Tabel Titel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titel1[/th]\n			[th=33,null]Titel2[/th]\n			[th=34,null]Titel3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n			[td=null,1]Tekst39[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE310'	=> '[size=130]Tabel Titel[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titel1[/th]\n			[th=33,null]Titel2[/th]\n			[th=34,null]Titel3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n		[/tr]\n			[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n			[td=null,1]Tekst39[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst110[/td]\n			[td=null,1]Tekst210[/td]\n			[td=null,1]Tekst310[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 4
*/
		'TABLE41'	=> '[size=130]Tabel Titel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titel1[/th]\n			[th=25,null]Titel2[/th]\n			[th=25,null]Titel3[/th]\n			[th=25,null]Titel4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n			[td=null,1]Tekst2[/td]\n			[td=null,1]Tekst3[/td]\n			[td=null,1]Tekst4[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE42'	=> '[size=130]Tabel Titel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titel1[/th]\n			[th=25,null]Titel2[/th]\n			[th=25,null]Titel3[/th]\n			[th=25,null]Titel4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE43'	=> '[size=130]Tabel Titel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titel1[/th]\n			[th=25,null]Titel2[/th]\n			[th=25,null]Titel3[/th]\n			[th=25,null]Titel4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE44'	=> '[size=130]Tabel Titel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titel1[/th]\n			[th=25,null]Titel2[/th]\n			[th=25,null]Titel3[/th]\n			[th=25,null]Titel4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE45'	=> '[size=130]Tabel Titel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titel1[/th]\n			[th=25,null]Titel2[/th]\n			[th=25,null]Titel3[/th]\n			[th=25,null]Titel4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE46'	=> '[size=130]Tabel Titel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titel1[/th]\n			[th=25,null]Titel2[/th]\n			[th=25,null]Titel3[/th]\n			[th=25,null]Titel4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE47'	=> '[size=130]Tabel Titel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titel1[/th]\n			[th=25,null]Titel2[/th]\n			[th=25,null]Titel3[/th]\n			[th=25,null]Titel4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE48'	=> '[size=130]Tabel Titel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titel1[/th]\n			[th=25,null]Titel2[/th]\n			[th=25,null]Titel3[/th]\n			[th=25,null]Titel4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE49'	=> '[size=130]Tabel Titel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titel1[/th]\n			[th=25,null]Titel2[/th]\n			[th=25,null]Titel3[/th]\n			[th=25,null]Titel4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n		[/tr]\n			[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n			[td=null,1]Tekst39[/td]\n			[td=null,1]Tekst49[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE410'	=> '[size=130]Tabel Titel[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titel1[/th]\n			[th=25,null]Titel2[/th]\n			[th=25,null]Titel3[/th]\n			[th=25,null]Titel4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n			[td=null,1]Tekst39[/td]\n			[td=null,1]Tekst49[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst110[/td]\n			[td=null,1]Tekst210[/td]\n			[td=null,1]Tekst310[/td]\n			[td=null,1]Tekst410[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 5
*/
		'TABLE51'	=> '[size=130]Tabel Titel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titel1[/th]\n			[th=20,null]Titel2[/th]\n			[th=20,null]Titel3[/th]\n			[th=20,null]Titel4[/th]\n			[th=20,null]Titel5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n			[td=null,1]Tekst2[/td]\n			[td=null,1]Tekst3[/td]\n			[td=null,1]Tekst4[/td]\n			[td=null,1]Tekst5[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE52'	=> '[size=130]Tabel Titel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titel1[/th]\n			[th=20,null]Titel2[/th]\n			[th=20,null]Titel3[/th]\n			[th=20,null]Titel4[/th]\n			[th=20,null]Titel5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE53'	=> '[size=130]Tabel Titel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titel1[/th]\n			[th=20,null]Titel2[/th]\n			[th=20,null]Titel3[/th]\n			[th=20,null]Titel4[/th]\n			[th=20,null]Titel5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE54'	=> '[size=130]Tabel Titel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titel1[/th]\n			[th=20,null]Titel2[/th]\n			[th=20,null]Titel3[/th]\n			[th=20,null]Titel4[/th]\n			[th=20,null]Titel5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE55'	=> '[size=130]Tabel Titel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titel1[/th]\n			[th=20,null]Titel2[/th]\n			[th=20,null]Titel3[/th]\n			[th=20,null]Titel4[/th]\n			[th=20,null]Titel5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE56'	=> '[size=130]Tabel Titel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titel1[/th]\n			[th=20,null]Titel2[/th]\n			[th=20,null]Titel3[/th]\n			[th=20,null]Titel4[/th]\n			[th=20,null]Titel5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE57'	=> '[size=130]Tabel Titel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titel1[/th]\n			[th=20,null]Titel2[/th]\n			[th=20,null]Titel3[/th]\n			[th=20,null]Titel4[/th]\n			[th=20,null]Titel5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE58'	=> '[size=130]Tabel Titel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titel1[/th]\n			[th=20,null]Titel2[/th]\n			[th=20,null]Titel3[/th]\n			[th=20,null]Titel4[/th]\n			[th=20,null]Titel5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n			[td=null,1]Tekst58[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE59'	=> '[size=130]Tabel Titel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titel1[/th]\n			[th=20,null]Titel2[/th]\n			[th=20,null]Titel3[/th]\n			[th=20,null]Titel4[/th]\n			[th=20,null]Titel5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n			[td=null,1]Tekst58[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n			[td=null,1]Tekst39[/td]\n			[td=null,1]Tekst49[/td]\n			[td=null,1]Tekst59[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE510'	=> '[size=130]Tabel Titel[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titel1[/th]\n			[th=20,null]Titel2[/th]\n			[th=20,null]Titel3[/th]\n			[th=20,null]Titel4[/th]\n			[th=20,null]Titel5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n			[td=null,1]Tekst58[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n			[td=null,1]Tekst39[/td]\n			[td=null,1]Tekst49[/td]\n			[td=null,1]Tekst59[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst110[/td]\n			[td=null,1]Tekst210[/td]\n			[td=null,1]Tekst310[/td]\n			[td=null,1]Tekst410[/td]\n			[td=null,1]Tekst510[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 6
*/
		'TABLE61'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titel1[/th]\n			[th=16,null]Titel2[/th]\n			[th=17,null]Titel3[/th]\n			[th=16,null]Titel4[/th]\n			[th=17,null]Titel5[/th]\n			[th=16,null]Titel6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n			[td=null,1]Tekst2[/td]\n			[td=null,1]Tekst3[/td]\n			[td=null,1]Tekst4[/td]\n			[td=null,1]Tekst5[/td]\n			[td=null,1]Tekst6[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE62'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titel1[/th]\n			[th=16,null]Titel2[/th]\n			[th=17,null]Titel3[/th]\n			[th=16,null]Titel4[/th]\n			[th=17,null]Titel5[/th]\n			[th=16,null]Titel6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE63'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titel1[/th]\n			[th=16,null]Titel2[/th]\n			[th=17,null]Titel3[/th]\n			[th=16,null]Titel4[/th]\n			[th=17,null]Titel5[/th]\n			[th=16,null]Titel6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE64'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titel1[/th]\n			[th=16,null]Titel2[/th]\n			[th=17,null]Titel3[/th]\n			[th=16,null]Titel4[/th]\n			[th=17,null]Titel5[/th]\n			[th=16,null]Titel6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE65'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titel1[/th]\n			[th=16,null]Titel2[/th]\n			[th=17,null]Titel3[/th]\n			[th=16,null]Titel4[/th]\n			[th=17,null]Titel5[/th]\n			[th=16,null]Titel6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE66'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titel1[/th]\n			[th=16,null]Titel2[/th]\n			[th=17,null]Titel3[/th]\n			[th=16,null]Titel4[/th]\n			[th=17,null]Titel5[/th]\n			[th=16,null]Titel6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n			[td=null,1]Tekst66[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE67'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titel1[/th]\n			[th=16,null]Titel2[/th]\n			[th=17,null]Titel3[/th]\n			[th=16,null]Titel4[/th]\n			[th=17,null]Titel5[/th]\n			[th=16,null]Titel6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n			[td=null,1]Tekst66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n			[td=null,1]Tekst67[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE68'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titel1[/th]\n			[th=16,null]Titel2[/th]\n			[th=17,null]Titel3[/th]\n			[th=16,null]Titel4[/th]\n			[th=17,null]Titel5[/th]\n			[th=16,null]Titel6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n			[td=null,1]Tekst66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n			[td=null,1]Tekst67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n			[td=null,1]Tekst58[/td]\n			[td=null,1]Tekst68[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE69'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titel1[/th]\n			[th=16,null]Titel2[/th]\n			[th=17,null]Titel3[/th]\n			[th=16,null]Titel4[/th]\n			[th=17,null]Titel5[/th]\n			[th=16,null]Titel6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n			[td=null,1]Tekst66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n			[td=null,1]Tekst67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n			[td=null,1]Tekst58[/td]\n			[td=null,1]Tekst68[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n			[td=null,1]Tekst39[/td]\n			[td=null,1]Tekst49[/td]\n			[td=null,1]Tekst59[/td]\n			[td=null,1]Tekst69[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE610'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titel1[/th]\n			[th=16,null]Titel2[/th]\n			[th=17,null]Titel3[/th]\n			[th=16,null]Titel4[/th]\n			[th=17,null]Titel5[/th]\n			[th=16,null]Titel6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n			[td=null,1]Tekst66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n			[td=null,1]Tekst67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n			[td=null,1]Tekst58[/td]\n			[td=null,1]Tekst68[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n			[td=null,1]Tekst39[/td]\n			[td=null,1]Tekst49[/td]\n			[td=null,1]Tekst59[/td]\n			[td=null,1]Tekst69[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst110[/td]\n			[td=null,1]Tekst210[/td]\n			[td=null,1]Tekst310[/td]\n			[td=null,1]Tekst410[/td]\n			[td=null,1]Tekst510[/td]\n			[td=null,1]Tekst610[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 7
*/
		'TABLE71'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Titel1[/th]\n			[th=14,null]Titel2[/th]\n			[th=14,null]Titel3[/th]\n			[th=14,null]Titel4[/th]\n			[th=14,null]Titel5[/th]\n			[th=14,null]Titel6[/th]\n			[th=16,null]Titel7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst1[/td]\n			[td=null,1]Tekst2[/td]\n			[td=null,1]Tekst3[/td]\n			[td=null,1]Tekst4[/td]\n			[td=null,1]Tekst5[/td]\n			[td=null,1]Tekst6[/td]\n			[td=null,1]Tekst71[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE72'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Titel1[/th]\n			[th=14,null]Titel2[/th]\n			[th=14,null]Titel3[/th]\n			[th=14,null]Titel4[/th]\n			[th=14,null]Titel5[/th]\n			[th=14,null]Titel6[/th]\n			[th=16,null]Titel7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n			[td=null,1]Tekst71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n			[td=null,1]Tekst72[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE73'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Titel1[/th]\n			[th=14,null]Titel2[/th]\n			[th=14,null]Titel3[/th]\n			[th=14,null]Titel4[/th]\n			[th=14,null]Titel5[/th]\n			[th=14,null]Titel6[/th]\n			[th=16,null]Titel7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n			[td=null,1]Tekst71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n			[td=null,1]Tekst72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n			[td=null,1]Tekst73[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE74'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Titel1[/th]\n			[th=14,null]Titel2[/th]\n			[th=14,null]Titel3[/th]\n			[th=14,null]Titel4[/th]\n			[th=14,null]Titel5[/th]\n			[th=14,null]Titel6[/th]\n			[th=16,null]Titel7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n			[td=null,1]Tekst71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n			[td=null,1]Tekst72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n			[td=null,1]Tekst73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n			[td=null,1]Tekst74[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE75'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Titel1[/th]\n			[th=14,null]Titel2[/th]\n			[th=14,null]Titel3[/th]\n			[th=14,null]Titel4[/th]\n			[th=14,null]Titel5[/th]\n			[th=14,null]Titel6[/th]\n			[th=16,null]Titel7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n			[td=null,1]Tekst71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n			[td=null,1]Tekst72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n			[td=null,1]Tekst73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n			[td=null,1]Tekst74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n			[td=null,1]Tekst75[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE76'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Titel1[/th]\n			[th=14,null]Titel2[/th]\n			[th=14,null]Titel3[/th]\n			[th=14,null]Titel4[/th]\n			[th=14,null]Titel5[/th]\n			[th=14,null]Titel6[/th]\n			[th=16,null]Titel7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n			[td=null,1]Tekst71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n			[td=null,1]Tekst72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n			[td=null,1]Tekst73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n			[td=null,1]Tekst74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n			[td=null,1]Tekst75[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n			[td=null,1]Tekst66[/td]\n			[td=null,1]Tekst76[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE77'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Titel1[/th]\n			[th=14,null]Titel2[/th]\n			[th=14,null]Titel3[/th]\n			[th=14,null]Titel4[/th]\n			[th=14,null]Titel5[/th]\n			[th=14,null]Titel6[/th]\n			[th=16,null]Titel7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n			[td=null,1]Tekst71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n			[td=null,1]Tekst72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n			[td=null,1]Tekst73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n			[td=null,1]Tekst74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n			[td=null,1]Tekst75[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n			[td=null,1]Tekst66[/td]\n			[td=null,1]Tekst76[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n			[td=null,1]Tekst67[/td]\n			[td=null,1]Tekst77[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE78'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Titel1[/th]\n			[th=14,null]Titel2[/th]\n			[th=14,null]Titel3[/th]\n			[th=14,null]Titel4[/th]\n			[th=14,null]Titel5[/th]\n			[th=14,null]Titel6[/th]\n			[th=16,null]Titel7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n			[td=null,1]Tekst71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n			[td=null,1]Tekst72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n			[td=null,1]Tekst73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n			[td=null,1]Tekst74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n			[td=null,1]Tekst75[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n			[td=null,1]Tekst66[/td]\n			[td=null,1]Tekst76[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n			[td=null,1]Tekst67[/td]\n			[td=null,1]Tekst77[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n			[td=null,1]Tekst58[/td]\n			[td=null,1]Tekst68[/td]\n			[td=null,1]Tekst78[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE79'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Titel1[/th]\n			[th=14,null]Titel2[/th]\n			[th=14,null]Titel3[/th]\n			[th=14,null]Titel4[/th]\n			[th=14,null]Titel5[/th]\n			[th=14,null]Titel6[/th]\n			[th=16,null]Titel7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n			[td=null,1]Tekst71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n			[td=null,1]Tekst72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n			[td=null,1]Tekst73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n			[td=null,1]Tekst74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n			[td=null,1]Tekst75[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n			[td=null,1]Tekst66[/td]\n			[td=null,1]Tekst76[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n			[td=null,1]Tekst67[/td]\n			[td=null,1]Tekst77[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n			[td=null,1]Tekst58[/td]\n			[td=null,1]Tekst68[/td]\n			[td=null,1]Tekst78[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n			[td=null,1]Tekst39[/td]\n			[td=null,1]Tekst49[/td]\n			[td=null,1]Tekst59[/td]\n			[td=null,1]Tekst69[/td]\n			[td=null,1]Tekst79[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE710'	=> '[size=130]Tabel Titel[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=14,null]Titel1[/th]\n			[th=14,null]Titel2[/th]\n			[th=14,null]Titel3[/th]\n			[th=14,null]Titel4[/th]\n			[th=14,null]Titel5[/th]\n			[th=14,null]Titel6[/th]\n			[th=16,null]Titel7[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Tekst11[/td]\n			[td=null,1]Tekst21[/td]\n			[td=null,1]Tekst31[/td]\n			[td=null,1]Tekst41[/td]\n			[td=null,1]Tekst51[/td]\n			[td=null,1]Tekst61[/td]\n			[td=null,1]Tekst71[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst12[/td]\n			[td=null,1]Tekst22[/td]\n			[td=null,1]Tekst32[/td]\n			[td=null,1]Tekst42[/td]\n			[td=null,1]Tekst52[/td]\n			[td=null,1]Tekst62[/td]\n			[td=null,1]Tekst72[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst13[/td]\n			[td=null,1]Tekst23[/td]\n			[td=null,1]Tekst33[/td]\n			[td=null,1]Tekst43[/td]\n			[td=null,1]Tekst53[/td]\n			[td=null,1]Tekst63[/td]\n			[td=null,1]Tekst73[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst14[/td]\n			[td=null,1]Tekst24[/td]\n			[td=null,1]Tekst34[/td]\n			[td=null,1]Tekst44[/td]\n			[td=null,1]Tekst54[/td]\n			[td=null,1]Tekst64[/td]\n			[td=null,1]Tekst74[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst15[/td]\n			[td=null,1]Tekst25[/td]\n			[td=null,1]Tekst35[/td]\n			[td=null,1]Tekst45[/td]\n			[td=null,1]Tekst55[/td]\n			[td=null,1]Tekst65[/td]\n			[td=null,1]Tekst75[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst16[/td]\n			[td=null,1]Tekst26[/td]\n			[td=null,1]Tekst36[/td]\n			[td=null,1]Tekst46[/td]\n			[td=null,1]Tekst56[/td]\n			[td=null,1]Tekst66[/td]\n			[td=null,1]Tekst76[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst17[/td]\n			[td=null,1]Tekst27[/td]\n			[td=null,1]Tekst37[/td]\n			[td=null,1]Tekst47[/td]\n			[td=null,1]Tekst57[/td]\n			[td=null,1]Tekst67[/td]\n			[td=null,1]Tekst77[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst18[/td]\n			[td=null,1]Tekst28[/td]\n			[td=null,1]Tekst38[/td]\n			[td=null,1]Tekst48[/td]\n			[td=null,1]Tekst58[/td]\n			[td=null,1]Tekst68[/td]\n			[td=null,1]Tekst78[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Tekst19[/td]\n			[td=null,1]Tekst29[/td]\n			[td=null,1]Tekst39[/td]\n			[td=null,1]Tekst49[/td]\n			[td=null,1]Tekst59[/td]\n			[td=null,1]Tekst69[/td]\n			[td=null,1]Tekst79[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Tekst110[/td]\n			[td=null,1]Tekst210[/td]\n			[td=null,1]Tekst310[/td]\n			[td=null,1]Tekst410[/td]\n			[td=null,1]Tekst510[/td]\n			[td=null,1]Tekst610[/td]\n			[td=null,1]Tekst710[/td]\n		[/tr]\n	[/tbody]\n[/table]',
	)
);
