<?php
/**
* @ package phpBB Extension - Tables
* @ copyright (c) 2015 Sniper_E - http://sniper-e.com
* @ license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
*
* @ French translation by Galixte (http://www.galixte.com)
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
/**
* Tables - French
*
* Buttons Titles for Selections and Guidelines
*/
		'TABLES_TITLE'				=> 'Table',
		'TABLE_TITLE'				=> 'Sélection de table',
		'TABLE_SELECTIONS_SHOW'		=> 'Afficher la sélection de table',
		'TABLE_SELECTIONS_HIDE'		=> 'Sélectionner une table',
		'TABLE_GUIDELINES_SHOW'		=> '<strong>Afficher l’aide concernant les tables</strong>',
		'TABLE_GUIDELINES'			=> '<strong>Aide concernant les tables :</strong> La valeur 75 utilisée dans cet exemple : [table=75,null] définie le pourcentage de largeur de la table.<br />La propriété « tleft » de l’exemple suivant : [table=75,tleft] définie le flottement de la table à gauche du Texte.<br />Voici les propriétés disponibles : « null », « tleft », « tright » ou « tcenter ».<br />Lorsque la propriété « tcenter » est utilisée dans la table, il est nécessaire d’utiliser la propriété [center] autour du Titrede la table afin de l’aligner.<br />Le pourcentage de largeur maximal de la table est de 98%.<br />Les valeurs [th=20,null], [th=30,null] et [th=50,null] correspondent aux pourcentages de largeur de chaque colonne.<br />L’addition des pourcentages utilisés dans les propriétés de type [th=#% doit nécessairement être égale à 100%.<br />La valeur « null » utilisée dans : [td=null,1] est une classe, utiliser « bg1 », « bg2 », ou autre si besoin et la valeur « 1 » définie l’attribue « colspan » de l’élément [td].<br />Si l’exemple ci-contre est utilisé : [td=null,2] il est nécessaire de retirer l’un des autres, tel que : [td=null,1] pour libérer la place sur deux colonnes.<br />L’exemple suivant :[tr=bg2] définie la classe de la rangée.<br /><br /><strong>Instructions :</strong> Cliquer sur le bouton « Aperçu » après la saisie du code de la table dans le cadre de saisie du Texte. Depuis la page de l’aperçu, modifier tous les noms des titres et des zones de Texteselon ses besoins. Ajuster tous les pourcentages de largeur pour équilibrer l’apparence de la table, cliquer à nouveau sur « Aperçu » puis sur « Envoyer ».',
/**
* Selections Column Numbers
*/
		'COLUMN_ONE'			=> '1 Colonne',
		'COLUMN_TWO'			=> '2 Colonnes',
		'COLUMN_THREE'			=> '3 Colonnes',
		'COLUMN_FOUR'			=> '4 Colonnes',
		'COLUMN_FIVE'			=> '5 Colonnes',
		'COLUMN_SIX'			=> '6 Colonnes',
/**
* Table Icon Selections Titles on Hover
*/
		'TABLE11_TITLE'			=> 'Table - 1 Colonne - 1 Rangée',
		'TABLE12_TITLE'			=> 'Table - 1 Colonne - 2 Rangées',
		'TABLE13_TITLE'			=> 'Table - 1 Colonne - 3 Rangées',
		'TABLE14_TITLE'			=> 'Table - 1 Colonne - 4 Rangées',
		'TABLE15_TITLE'			=> 'Table - 1 Colonne - 5 Rangées',
		'TABLE16_TITLE'			=> 'Table - 1 Colonne - 6 Rangées',
		'TABLE17_TITLE'			=> 'Table - 1 Colonne - 7 Rangées',
		'TABLE18_TITLE'			=> 'Table - 1 Colonne - 8 Rangées',
		'TABLE19_TITLE'			=> 'Table - 1 Colonne - 9 Rangées',
		'TABLE110_TITLE'		=> 'Table - 1 Colonne - 10 Rangées',
		'TABLE21_TITLE'			=> 'Table - 2 Colonne - 1 Rangée',
		'TABLE22_TITLE'			=> 'Table - 2 Colonnes - 2 Rangées',
		'TABLE23_TITLE'			=> 'Table - 2 Colonnes - 3 Rangées',
		'TABLE24_TITLE'			=> 'Table - 2 Colonnes - 4 Rangées',
		'TABLE25_TITLE'			=> 'Table - 2 Colonnes - 5 Rangées',
		'TABLE26_TITLE'			=> 'Table - 2 Colonnes - 6 Rangées',
		'TABLE27_TITLE'			=> 'Table - 2 Colonnes - 7 Rangées',
		'TABLE28_TITLE'			=> 'Table - 2 Colonnes - 8 Rangées',
		'TABLE29_TITLE'			=> 'Table - 2 Colonnes - 9 Rangées',
		'TABLE210_TITLE'		=> 'Table - 2 Colonnes - 10 Rangées',
		'TABLE31_TITLE'			=> 'Table - 3 Colonnes - 1 Rangée',
		'TABLE32_TITLE'			=> 'Table - 3 Colonnes - 2 Rangées',
		'TABLE33_TITLE'			=> 'Table - 3 Colonnes - 3 Rangées',
		'TABLE34_TITLE'			=> 'Table - 3 Colonnes - 4 Rangées',
		'TABLE35_TITLE'			=> 'Table - 3 Colonnes - 5 Rangées',
		'TABLE36_TITLE'			=> 'Table - 3 Colonnes - 6 Rangées',
		'TABLE37_TITLE'			=> 'Table - 3 Colonnes - 7 Rangées',
		'TABLE38_TITLE'			=> 'Table - 3 Colonnes - 8 Rangées',
		'TABLE39_TITLE'			=> 'Table - 3 Colonnes - 9 Rangées',
		'TABLE310_TITLE'		=> 'Table - 3 Colonnes - 10 Rangées',
		'TABLE41_TITLE'			=> 'Table - 4 Colonnes - 1 Rangée',
		'TABLE42_TITLE'			=> 'Table - 4 Colonnes - 2 Rangées',
		'TABLE43_TITLE'			=> 'Table - 4 Colonnes - 3 Rangées',
		'TABLE44_TITLE'			=> 'Table - 4 Colonnes - 4 Rangées',
		'TABLE45_TITLE'			=> 'Table - 4 Colonnes - 5 Rangées',
		'TABLE46_TITLE'			=> 'Table - 4 Colonnes - 6 Rangées',
		'TABLE47_TITLE'			=> 'Table - 4 Colonnes - 7 Rangées',
		'TABLE48_TITLE'			=> 'Table - 4 Colonnes - 8 Rangées',
		'TABLE49_TITLE'			=> 'Table - 4 Colonnes - 9 Rangées',
		'TABLE410_TITLE'		=> 'Table - 4 Colonnes - 10 Rangées',
		'TABLE51_TITLE'			=> 'Table - 5 Colonnes - 1 Rangée',
		'TABLE52_TITLE'			=> 'Table - 5 Colonnes - 2 Rangées',
		'TABLE53_TITLE'			=> 'Table - 5 Colonnes - 3 Rangées',
		'TABLE54_TITLE'			=> 'Table - 5 Colonnes - 4 Rangées',
		'TABLE55_TITLE'			=> 'Table - 5 Colonnes - 5 Rangées',
		'TABLE56_TITLE'			=> 'Table - 5 Colonnes - 6 Rangées',
		'TABLE57_TITLE'			=> 'Table - 5 Colonnes - 7 Rangées',
		'TABLE58_TITLE'			=> 'Table - 5 Colonnes - 8 Rangées',
		'TABLE59_TITLE'			=> 'Table - 5 Colonnes - 9 Rangées',
		'TABLE510_TITLE'		=> 'Table - 5 Colonnes - 10 Rangées',
		'TABLE61_TITLE'			=> 'Table - 6 Colonnes - 1 Rangée',
		'TABLE62_TITLE'			=> 'Table - 6 Colonnes - 2 Rangées',
		'TABLE63_TITLE'			=> 'Table - 6 Colonnes - 3 Rangées',
		'TABLE64_TITLE'			=> 'Table - 6 Colonnes - 4 Rangées',
		'TABLE65_TITLE'			=> 'Table - 6 Colonnes - 5 Rangées',
		'TABLE66_TITLE'			=> 'Table - 6 Colonnes - 6 Rangées',
		'TABLE67_TITLE'			=> 'Table - 6 Colonnes - 7 Rangées',
		'TABLE68_TITLE'			=> 'Table - 6 Colonnes - 8 Rangées',
		'TABLE69_TITLE'			=> 'Table - 6 Colonnes - 9 Rangées',
		'TABLE610_TITLE'		=> 'Table - 6 Colonnes - 10 Rangées',
/**
* Tables Posted by Columns and Rows
*
* Column 1
*/
		'TABLE11'	=> '[size=130]Titrede la table[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titre[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE12'	=> '[size=130]Titrede la table[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titre[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte2[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE13'	=> '[size=130]Titrede la table[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titre[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte3[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE14'	=> '[size=130]Titrede la table[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titre[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte4[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE15'	=> '[size=130]Titrede la table[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titre[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte5[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE16'	=> '[size=130]Titrede la table[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titre[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte6[/td]\n			[/tr]\n	[/tbody]\n[/table]',
		'TABLE17'	=> '[size=130]Titrede la table[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titre[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte7[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE18'	=> '[size=130]Titrede la table[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titre[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte8[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE19'	=> '[size=130]Titrede la table[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titre[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte8[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte9[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE110'	=> '[size=130]Titrede la table[/size]\n[table=15,null]\n	[thead]\n		[tr=textleft]\n			[th=100,null]Titre[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte2[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte3[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte4[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte5[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte6[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte7[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte8[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte9[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte10[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 2
*/
		'TABLE21'	=> '[size=130]Titrede la table[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titre1[/th]\n			[th=50,null]Titre2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n			[td=null,1]Texte2[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE22'	=> '[size=130]Titrede la table[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titre1[/th]\n			[th=50,null]Titre2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE23'	=> '[size=130]Titrede la table[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titre1[/th]\n			[th=50,null]Titre2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE24'	=> '[size=130]Titrede la table[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titre1[/th]\n			[th=50,null]Titre2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE25'	=> '[size=130]Titrede la table[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titre1[/th]\n			[th=50,null]Titre2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE26'	=> '[size=130]Titrede la table[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titre1[/th]\n			[th=50,null]Titre2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE27'	=> '[size=130]Titrede la table[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titre1[/th]\n			[th=50,null]Titre2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE28'	=> '[size=130]Titrede la table[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titre1[/th]\n			[th=50,null]Titre2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE29'	=> '[size=130]Titrede la table[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titre1[/th]\n			[th=50,null]Titre2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte19[/td]\n			[td=null,1]Texte29[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE210'	=> '[size=130]Titrede la table[/size]\n[table=30,null]\n	[thead]\n		[tr=textleft]\n			[th=50,null]Titre1[/th]\n			[th=50,null]Titre2[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte19[/td]\n			[td=null,1]Texte29[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte110[/td]\n			[td=null,1]Texte210[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 3
*/
		'TABLE31'	=> '[size=130]Titrede la table[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titre1[/th]\n			[th=33,null]Titre2[/th]\n			[th=34,null]Titre3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n			[td=null,1]Texte2[/td]\n			[td=null,1]Texte3[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE32'	=> '[size=130]Titrede la table[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titre1[/th]\n			[th=33,null]Titre2[/th]\n			[th=34,null]Titre3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE33'	=> '[size=130]Titrede la table[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titre1[/th]\n			[th=33,null]Titre2[/th]\n			[th=34,null]Titre3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE34'	=> '[size=130]Titrede la table[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titre1[/th]\n			[th=33,null]Titre2[/th]\n			[th=34,null]Titre3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE35'	=> '[size=130]Titrede la table[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titre1[/th]\n			[th=33,null]Titre2[/th]\n			[th=34,null]Titre3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE36'	=> '[size=130]Titrede la table[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titre1[/th]\n			[th=33,null]Titre2[/th]\n			[th=34,null]Titre3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE37'	=> '[size=130]Titrede la table[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titre1[/th]\n			[th=33,null]Titre2[/th]\n			[th=34,null]Titre3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE38'	=> '[size=130]Titrede la table[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titre1[/th]\n			[th=33,null]Titre2[/th]\n			[th=34,null]Titre3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE39'	=> '[size=130]Titrede la table[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titre1[/th]\n			[th=33,null]Titre2[/th]\n			[th=34,null]Titre3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte19[/td]\n			[td=null,1]Texte29[/td]\n			[td=null,1]Texte39[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE310'	=> '[size=130]Titrede la table[/size]\n[table=45,null]\n	[thead]\n		[tr=textleft]\n			[th=33,null]Titre1[/th]\n			[th=33,null]Titre2[/th]\n			[th=34,null]Titre3[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n		[/tr]\n			[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte19[/td]\n			[td=null,1]Texte29[/td]\n			[td=null,1]Texte39[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte110[/td]\n			[td=null,1]Texte210[/td]\n			[td=null,1]Texte310[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 4
*/
		'TABLE41'	=> '[size=130]Titrede la table[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titre1[/th]\n			[th=25,null]Titre2[/th]\n			[th=25,null]Titre3[/th]\n			[th=25,null]Titre4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n			[td=null,1]Texte2[/td]\n			[td=null,1]Texte3[/td]\n			[td=null,1]Texte4[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE42'	=> '[size=130]Titrede la table[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titre1[/th]\n			[th=25,null]Titre2[/th]\n			[th=25,null]Titre3[/th]\n			[th=25,null]Titre4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE43'	=> '[size=130]Titrede la table[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titre1[/th]\n			[th=25,null]Titre2[/th]\n			[th=25,null]Titre3[/th]\n			[th=25,null]Titre4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE44'	=> '[size=130]Titrede la table[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titre1[/th]\n			[th=25,null]Titre2[/th]\n			[th=25,null]Titre3[/th]\n			[th=25,null]Titre4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE45'	=> '[size=130]Titrede la table[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titre1[/th]\n			[th=25,null]Titre2[/th]\n			[th=25,null]Titre3[/th]\n			[th=25,null]Titre4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE46'	=> '[size=130]Titrede la table[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titre1[/th]\n			[th=25,null]Titre2[/th]\n			[th=25,null]Titre3[/th]\n			[th=25,null]Titre4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE47'	=> '[size=130]Titrede la table[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titre1[/th]\n			[th=25,null]Titre2[/th]\n			[th=25,null]Titre3[/th]\n			[th=25,null]Titre4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE48'	=> '[size=130]Titrede la table[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titre1[/th]\n			[th=25,null]Titre2[/th]\n			[th=25,null]Titre3[/th]\n			[th=25,null]Titre4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n			[td=null,1]Texte48[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE49'	=> '[size=130]Titrede la table[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titre1[/th]\n			[th=25,null]Titre2[/th]\n			[th=25,null]Titre3[/th]\n			[th=25,null]Titre4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n		[/tr]\n			[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n			[td=null,1]Texte48[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte19[/td]\n			[td=null,1]Texte29[/td]\n			[td=null,1]Texte39[/td]\n			[td=null,1]Texte49[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE410'	=> '[size=130]Titrede la table[/size]\n[table=60,null]\n	[thead]\n		[tr=textleft]\n			[th=25,null]Titre1[/th]\n			[th=25,null]Titre2[/th]\n			[th=25,null]Titre3[/th]\n			[th=25,null]Titre4[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n			[td=null,1]Texte48[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte19[/td]\n			[td=null,1]Texte29[/td]\n			[td=null,1]Texte39[/td]\n			[td=null,1]Texte49[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte110[/td]\n			[td=null,1]Texte210[/td]\n			[td=null,1]Texte310[/td]\n			[td=null,1]Texte410[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 5
*/
		'TABLE51'	=> '[size=130]Titrede la table[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titre1[/th]\n			[th=20,null]Titre2[/th]\n			[th=20,null]Titre3[/th]\n			[th=20,null]Titre4[/th]\n			[th=20,null]Titre5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n			[td=null,1]Texte2[/td]\n			[td=null,1]Texte3[/td]\n			[td=null,1]Texte4[/td]\n			[td=null,1]Texte5[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE52'	=> '[size=130]Titrede la table[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titre1[/th]\n			[th=20,null]Titre2[/th]\n			[th=20,null]Titre3[/th]\n			[th=20,null]Titre4[/th]\n			[th=20,null]Titre5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE53'	=> '[size=130]Titrede la table[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titre1[/th]\n			[th=20,null]Titre2[/th]\n			[th=20,null]Titre3[/th]\n			[th=20,null]Titre4[/th]\n			[th=20,null]Titre5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE54'	=> '[size=130]Titrede la table[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titre1[/th]\n			[th=20,null]Titre2[/th]\n			[th=20,null]Titre3[/th]\n			[th=20,null]Titre4[/th]\n			[th=20,null]Titre5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE55'	=> '[size=130]Titrede la table[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titre1[/th]\n			[th=20,null]Titre2[/th]\n			[th=20,null]Titre3[/th]\n			[th=20,null]Titre4[/th]\n			[th=20,null]Titre5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE56'	=> '[size=130]Titrede la table[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titre1[/th]\n			[th=20,null]Titre2[/th]\n			[th=20,null]Titre3[/th]\n			[th=20,null]Titre4[/th]\n			[th=20,null]Titre5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n			[td=null,1]Texte56[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE57'	=> '[size=130]Titrede la table[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titre1[/th]\n			[th=20,null]Titre2[/th]\n			[th=20,null]Titre3[/th]\n			[th=20,null]Titre4[/th]\n			[th=20,null]Titre5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n			[td=null,1]Texte56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n			[td=null,1]Texte57[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE58'	=> '[size=130]Titrede la table[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titre1[/th]\n			[th=20,null]Titre2[/th]\n			[th=20,null]Titre3[/th]\n			[th=20,null]Titre4[/th]\n			[th=20,null]Titre5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n			[td=null,1]Texte56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n			[td=null,1]Texte57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n			[td=null,1]Texte48[/td]\n			[td=null,1]Texte58[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE59'	=> '[size=130]Titrede la table[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titre1[/th]\n			[th=20,null]Titre2[/th]\n			[th=20,null]Titre3[/th]\n			[th=20,null]Titre4[/th]\n			[th=20,null]Titre5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n			[td=null,1]Texte56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n			[td=null,1]Texte57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n			[td=null,1]Texte48[/td]\n			[td=null,1]Texte58[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte19[/td]\n			[td=null,1]Texte29[/td]\n			[td=null,1]Texte39[/td]\n			[td=null,1]Texte49[/td]\n			[td=null,1]Texte59[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE510'	=> '[size=130]Titrede la table[/size]\n[table=75,null]\n	[thead]\n		[tr=textleft]\n			[th=20,null]Titre1[/th]\n			[th=20,null]Titre2[/th]\n			[th=20,null]Titre3[/th]\n			[th=20,null]Titre4[/th]\n			[th=20,null]Titre5[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n			[td=null,1]Texte56[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n			[td=null,1]Texte57[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n			[td=null,1]Texte48[/td]\n			[td=null,1]Texte58[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte19[/td]\n			[td=null,1]Texte29[/td]\n			[td=null,1]Texte39[/td]\n			[td=null,1]Texte49[/td]\n			[td=null,1]Texte59[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte110[/td]\n			[td=null,1]Texte210[/td]\n			[td=null,1]Texte310[/td]\n			[td=null,1]Texte410[/td]\n			[td=null,1]Texte510[/td]\n		[/tr]\n	[/tbody]\n[/table]',
/**
* Column 6
*/
		'TABLE61'	=> '[size=130]Titrede la table[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titre1[/th]\n			[th=16,null]Titre2[/th]\n			[th=17,null]Titre3[/th]\n			[th=16,null]Titre4[/th]\n			[th=17,null]Titre5[/th]\n			[th=16,null]Titre6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte1[/td]\n			[td=null,1]Texte2[/td]\n			[td=null,1]Texte3[/td]\n			[td=null,1]Texte4[/td]\n			[td=null,1]Texte5[/td]\n			[td=null,1]Texte6[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE62'	=> '[size=130]Titrede la table[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titre1[/th]\n			[th=16,null]Titre2[/th]\n			[th=17,null]Titre3[/th]\n			[th=16,null]Titre4[/th]\n			[th=17,null]Titre5[/th]\n			[th=16,null]Titre6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n			[td=null,1]Texte61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n			[td=null,1]Texte62[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE63'	=> '[size=130]Titrede la table[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titre1[/th]\n			[th=16,null]Titre2[/th]\n			[th=17,null]Titre3[/th]\n			[th=16,null]Titre4[/th]\n			[th=17,null]Titre5[/th]\n			[th=16,null]Titre6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n			[td=null,1]Texte61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n			[td=null,1]Texte62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n			[td=null,1]Texte63[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE64'	=> '[size=130]Titrede la table[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titre1[/th]\n			[th=16,null]Titre2[/th]\n			[th=17,null]Titre3[/th]\n			[th=16,null]Titre4[/th]\n			[th=17,null]Titre5[/th]\n			[th=16,null]Titre6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n			[td=null,1]Texte61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n			[td=null,1]Texte62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n			[td=null,1]Texte63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n			[td=null,1]Texte64[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE65'	=> '[size=130]Titrede la table[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titre1[/th]\n			[th=16,null]Titre2[/th]\n			[th=17,null]Titre3[/th]\n			[th=16,null]Titre4[/th]\n			[th=17,null]Titre5[/th]\n			[th=16,null]Titre6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n			[td=null,1]Texte61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n			[td=null,1]Texte62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n			[td=null,1]Texte63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n			[td=null,1]Texte64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n			[td=null,1]Texte65[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE66'	=> '[size=130]Titrede la table[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titre1[/th]\n			[th=16,null]Titre2[/th]\n			[th=17,null]Titre3[/th]\n			[th=16,null]Titre4[/th]\n			[th=17,null]Titre5[/th]\n			[th=16,null]Titre6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n			[td=null,1]Texte61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n			[td=null,1]Texte62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n			[td=null,1]Texte63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n			[td=null,1]Texte64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n			[td=null,1]Texte65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n			[td=null,1]Texte56[/td]\n			[td=null,1]Texte66[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE67'	=> '[size=130]Titrede la table[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titre1[/th]\n			[th=16,null]Titre2[/th]\n			[th=17,null]Titre3[/th]\n			[th=16,null]Titre4[/th]\n			[th=17,null]Titre5[/th]\n			[th=16,null]Titre6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n			[td=null,1]Texte61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n			[td=null,1]Texte62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n			[td=null,1]Texte63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n			[td=null,1]Texte64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n			[td=null,1]Texte65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n			[td=null,1]Texte56[/td]\n			[td=null,1]Texte66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n			[td=null,1]Texte57[/td]\n			[td=null,1]Texte67[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE68'	=> '[size=130]Titrede la table[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titre1[/th]\n			[th=16,null]Titre2[/th]\n			[th=17,null]Titre3[/th]\n			[th=16,null]Titre4[/th]\n			[th=17,null]Titre5[/th]\n			[th=16,null]Titre6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n			[td=null,1]Texte61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n			[td=null,1]Texte62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n			[td=null,1]Texte63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n			[td=null,1]Texte64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n			[td=null,1]Texte65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n			[td=null,1]Texte56[/td]\n			[td=null,1]Texte66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n			[td=null,1]Texte57[/td]\n			[td=null,1]Texte67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n			[td=null,1]Texte48[/td]\n			[td=null,1]Texte58[/td]\n			[td=null,1]Texte68[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE69'	=> '[size=130]Titrede la table[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titre1[/th]\n			[th=16,null]Titre2[/th]\n			[th=17,null]Titre3[/th]\n			[th=16,null]Titre4[/th]\n			[th=17,null]Titre5[/th]\n			[th=16,null]Titre6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n			[td=null,1]Texte61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n			[td=null,1]Texte62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n			[td=null,1]Texte63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n			[td=null,1]Texte64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n			[td=null,1]Texte65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n			[td=null,1]Texte56[/td]\n			[td=null,1]Texte66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n			[td=null,1]Texte57[/td]\n			[td=null,1]Texte67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n			[td=null,1]Texte48[/td]\n			[td=null,1]Texte58[/td]\n			[td=null,1]Texte68[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte19[/td]\n			[td=null,1]Texte29[/td]\n			[td=null,1]Texte39[/td]\n			[td=null,1]Texte49[/td]\n			[td=null,1]Texte59[/td]\n			[td=null,1]Texte69[/td]\n		[/tr]\n	[/tbody]\n[/table]',
		'TABLE610'	=> '[size=130]Titrede la table[/size]\n[table=90,null]\n	[thead]\n		[tr=textleft]\n			[th=17,null]Titre1[/th]\n			[th=16,null]Titre2[/th]\n			[th=17,null]Titre3[/th]\n			[th=16,null]Titre4[/th]\n			[th=17,null]Titre5[/th]\n			[th=16,null]Titre6[/th]\n		[/tr]\n	[/thead]\n	[tbody]\n		[tr=bg2]\n			[td=null,1]Texte11[/td]\n			[td=null,1]Texte21[/td]\n			[td=null,1]Texte31[/td]\n			[td=null,1]Texte41[/td]\n			[td=null,1]Texte51[/td]\n			[td=null,1]Texte61[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte12[/td]\n			[td=null,1]Texte22[/td]\n			[td=null,1]Texte32[/td]\n			[td=null,1]Texte42[/td]\n			[td=null,1]Texte52[/td]\n			[td=null,1]Texte62[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte13[/td]\n			[td=null,1]Texte23[/td]\n			[td=null,1]Texte33[/td]\n			[td=null,1]Texte43[/td]\n			[td=null,1]Texte53[/td]\n			[td=null,1]Texte63[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte14[/td]\n			[td=null,1]Texte24[/td]\n			[td=null,1]Texte34[/td]\n			[td=null,1]Texte44[/td]\n			[td=null,1]Texte54[/td]\n			[td=null,1]Texte64[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte15[/td]\n			[td=null,1]Texte25[/td]\n			[td=null,1]Texte35[/td]\n			[td=null,1]Texte45[/td]\n			[td=null,1]Texte55[/td]\n			[td=null,1]Texte65[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte16[/td]\n			[td=null,1]Texte26[/td]\n			[td=null,1]Texte36[/td]\n			[td=null,1]Texte46[/td]\n			[td=null,1]Texte56[/td]\n			[td=null,1]Texte66[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte17[/td]\n			[td=null,1]Texte27[/td]\n			[td=null,1]Texte37[/td]\n			[td=null,1]Texte47[/td]\n			[td=null,1]Texte57[/td]\n			[td=null,1]Texte67[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte18[/td]\n			[td=null,1]Texte28[/td]\n			[td=null,1]Texte38[/td]\n			[td=null,1]Texte48[/td]\n			[td=null,1]Texte58[/td]\n			[td=null,1]Texte68[/td]\n		[/tr]\n		[tr=bg2]\n			[td=null,1]Texte19[/td]\n			[td=null,1]Texte29[/td]\n			[td=null,1]Texte39[/td]\n			[td=null,1]Texte49[/td]\n			[td=null,1]Texte59[/td]\n			[td=null,1]Texte69[/td]\n		[/tr]\n		[tr=bg1]\n			[td=null,1]Texte110[/td]\n			[td=null,1]Texte210[/td]\n			[td=null,1]Texte310[/td]\n			[td=null,1]Texte410[/td]\n			[td=null,1]Texte510[/td]\n			[td=null,1]Texte610[/td]\n		[/tr]\n	[/tbody]\n[/table]',
	)
);