<?php
/**
 *
 * Tables. An extension for the phpBB Forum Software package.
 * French translation by Galixte (http://www.galixte.com)
 *
 * @copyright (c) 2017 Sniper_E <http://sniper-e.com>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 */

/**
 * DO NOT CHANGE
 */
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ « » “ ” …
//

$lang = array_merge($lang, array(
/**
* Tables - English Language
*
* Buttons Titles for Selections and Guidelines
*/
		'TABLE_TITLE'				=> 'Sélection de table',
		'TABLE_SELECTIONS_SHOW'		=> 'Afficher la sélection de table',
		'TABLE_SELECTIONS_HIDE'		=> 'Sélectionner une table',
		'TABLE_GUIDELINES_SHOW'		=> '<strong>Afficher l’aide concernant les tables</strong>',
		'TABLE_GUIDELINES'			=> '<strong>Aide concernant les tables :</strong> La valeur 75 utilisée dans cet exemple : [table=75,null] définie le pourcentage de largeur de la table.<br />La propriété « tleft » de l’exemple suivant : [table=75,tleft] définie le flottement de la table à gauche du texte.<br />Voici les propriétés disponibles : « null », « tleft », « tright » ou « tcenter ».<br />Lorsque la propriété « tcenter » est utilisée dans la table, il est nécessaire d’utiliser la propriété [center] autour du titre de la table afin de l’aligner.<br />Le pourcentage de largeur maximal de la table est de 98%.<br />Les valeurs [th=20,null], [th=30,null] et [th=50,null] correspondent aux pourcentages de largeur de chaque colonne.<br />L’addition des pourcentages utilisés dans les propriétés de type [th=#% doit nécessairement être égale à 100%.<br />La valeur « null » utilisée dans : [td=null,1] est une classe, utiliser « bg1 », « bg2 », ou autre si besoin et la valeur « 1 » définie l’attribue « colspan » de l’élément [td].<br />Si l’exemple ci-contre est utilisé : [td=null,2] il est nécessaire de retirer l’un des autres, tel que : [td=null,1] pour libérer la place sur deux colonnes.<br />L’exemple suivant :[tr=bg2] définie la classe de la rangée.<br /><br /><strong>Instructions :</strong> Cliquer sur le bouton « Aperçu » après la saisie du code de la table dans le cadre de saisie du texte. Depuis la page de l’aperçu, modifier tous les noms des titres et des zones de texte selon ses besoins. Ajuster tous les pourcentages de largeur pour équilibrer l’apparence de la table, cliquer à nouveau sur « Aperçu » puis sur « Envoyer ».',
/**
* Selections Column Numbers
*/
		'COLUMN_ONE'			=> '1 colonne',
		'COLUMN_TWO'			=> '2 colonnes',
		'COLUMN_THREE'			=> '3 colonnes',
		'COLUMN_FOUR'			=> '4 colonnes',
		'COLUMN_FIVE'			=> '5 colonnes',
		'COLUMN_SIX'			=> '6 colonnes',
/**
* Table Icon Selections Titles on Hover
*/
		'TABLE11_TITLE'			=> 'Table - 1 colonne - 1 rangée',
		'TABLE12_TITLE'			=> 'Table - 1 colonne - 2 rangées',
		'TABLE13_TITLE'			=> 'Table - 1 colonne - 3 rangées',
		'TABLE14_TITLE'			=> 'Table - 1 colonne - 4 rangées',
		'TABLE15_TITLE'			=> 'Table - 1 colonne - 5 rangées',
		'TABLE16_TITLE'			=> 'Table - 1 colonne - 6 rangées',
		'TABLE17_TITLE'			=> 'Table - 1 colonne - 7 rangées',
		'TABLE18_TITLE'			=> 'Table - 1 colonne - 8 rangées',
		'TABLE19_TITLE'			=> 'Table - 1 colonne - 9 rangées',
		'TABLE110_TITLE'		=> 'Table - 1 colonne - 10 rangées',
		'TABLE21_TITLE'			=> 'Table - 2 colonnes - 1 rangée',
		'TABLE22_TITLE'			=> 'Table - 2 colonnes - 2 rangées',
		'TABLE23_TITLE'			=> 'Table - 2 colonnes - 3 rangées',
		'TABLE24_TITLE'			=> 'Table - 2 colonnes - 4 rangées',
		'TABLE25_TITLE'			=> 'Table - 2 colonnes - 5 rangées',
		'TABLE26_TITLE'			=> 'Table - 2 colonnes - 6 rangées',
		'TABLE27_TITLE'			=> 'Table - 2 colonnes - 7 rangées',
		'TABLE28_TITLE'			=> 'Table - 2 colonnes - 8 rangées',
		'TABLE29_TITLE'			=> 'Table - 2 colonnes - 9 rangées',
		'TABLE210_TITLE'		=> 'Table - 2 colonnes - 10 rangées',
		'TABLE31_TITLE'			=> 'Table - 3 colonnes - 1 rangée',
		'TABLE32_TITLE'			=> 'Table - 3 colonnes - 2 rangées',
		'TABLE33_TITLE'			=> 'Table - 3 colonnes - 3 rangées',
		'TABLE34_TITLE'			=> 'Table - 3 colonnes - 4 rangées',
		'TABLE35_TITLE'			=> 'Table - 3 colonnes - 5 rangées',
		'TABLE36_TITLE'			=> 'Table - 3 colonnes - 6 rangées',
		'TABLE37_TITLE'			=> 'Table - 3 colonnes - 7 rangées',
		'TABLE38_TITLE'			=> 'Table - 3 colonnes - 8 rangées',
		'TABLE39_TITLE'			=> 'Table - 3 colonnes - 9 rangées',
		'TABLE310_TITLE'		=> 'Table - 3 colonnes - 10 rangées',
		'TABLE41_TITLE'			=> 'Table - 4 colonnes - 1 rangée',
		'TABLE42_TITLE'			=> 'Table - 4 colonnes - 2 rangées',
		'TABLE43_TITLE'			=> 'Table - 4 colonnes - 3 rangées',
		'TABLE44_TITLE'			=> 'Table - 4 colonnes - 4 rangées',
		'TABLE45_TITLE'			=> 'Table - 4 colonnes - 5 rangées',
		'TABLE46_TITLE'			=> 'Table - 4 colonnes - 6 rangées',
		'TABLE47_TITLE'			=> 'Table - 4 colonnes - 7 rangées',
		'TABLE48_TITLE'			=> 'Table - 4 colonnes - 8 rangées',
		'TABLE49_TITLE'			=> 'Table - 4 colonnes - 9 rangées',
		'TABLE410_TITLE'		=> 'Table - 4 colonnes - 10 rangées',
		'TABLE51_TITLE'			=> 'Table - 5 colonnes - 1 rangée',
		'TABLE52_TITLE'			=> 'Table - 5 colonnes - 2 rangées',
		'TABLE53_TITLE'			=> 'Table - 5 colonnes - 3 rangées',
		'TABLE54_TITLE'			=> 'Table - 5 colonnes - 4 rangées',
		'TABLE55_TITLE'			=> 'Table - 5 colonnes - 5 rangées',
		'TABLE56_TITLE'			=> 'Table - 5 colonnes - 6 rangées',
		'TABLE57_TITLE'			=> 'Table - 5 colonnes - 7 rangées',
		'TABLE58_TITLE'			=> 'Table - 5 colonnes - 8 rangées',
		'TABLE59_TITLE'			=> 'Table - 5 colonnes - 9 rangées',
		'TABLE510_TITLE'		=> 'Table - 5 colonnes - 10 rangées',
		'TABLE61_TITLE'			=> 'Table - 6 colonnes - 1 rangée',
		'TABLE62_TITLE'			=> 'Table - 6 colonnes - 2 rangées',
		'TABLE63_TITLE'			=> 'Table - 6 colonnes - 3 rangées',
		'TABLE64_TITLE'			=> 'Table - 6 colonnes - 4 rangées',
		'TABLE65_TITLE'			=> 'Table - 6 colonnes - 5 rangées',
		'TABLE66_TITLE'			=> 'Table - 6 colonnes - 6 rangées',
		'TABLE67_TITLE'			=> 'Table - 6 colonnes - 7 rangées',
		'TABLE68_TITLE'			=> 'Table - 6 colonnes - 8 rangées',
		'TABLE69_TITLE'			=> 'Table - 6 colonnes - 9 rangées',
		'TABLE610_TITLE'		=> 'Table - 6 colonnes - 10 rangées',
/**
* Tables Posted by Columns and Rows - DO NOT CHANGE
*
* Column 1
*/
		'TABLE11'	=> '[size=130]Titre de la table[/size]\n[table=15,null][thead][tr=textleft][th=100,null]Titre[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte[/td][/tr][/tbody][/table]',
		'TABLE12'	=> '[size=130]Titre de la table[/size]\n[table=15,null][thead][tr=textleft][th=100,null]Titre[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][/tr]\n[tr=bg1][td=null,1]Texte 2[/td][/tr][/tbody][/table]',
		'TABLE13'	=> '[size=130]Titre de la table[/size]\n[table=15,null][thead][tr=textleft][th=100,null]Titre[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][/tr]\n[tr=bg1][td=null,1]Texte 2[/td][/tr]\n[tr=bg2][td=null,1]Texte 3[/td][/tr][/tbody][/table]',
		'TABLE14'	=> '[size=130]Titre de la table[/size]\n[table=15,null][thead][tr=textleft][th=100,null]Titre[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][/tr]\n[tr=bg1][td=null,1]Texte 2[/td][/tr]\n[tr=bg2][td=null,1]Texte 3[/td][/tr]\n[tr=bg1][td=null,1]Texte 4[/td][/tr][/tbody][/table]',
		'TABLE15'	=> '[size=130]Titre de la table[/size]\n[table=15,null][thead][tr=textleft][th=100,null]Titre[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][/tr]\n[tr=bg1][td=null,1]Texte 2[/td][/tr]\n[tr=bg2][td=null,1]Texte 3[/td][/tr]\n[tr=bg1][td=null,1]Texte 4[/td][/tr]\n[tr=bg2][td=null,1]Texte 5[/td][/tr][/tbody][/table]',
		'TABLE16'	=> '[size=130]Titre de la table[/size]\n[table=15,null][thead][tr=textleft][th=100,null]Titre[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][/tr]\n[tr=bg1][td=null,1]Texte 2[/td][/tr]\n[tr=bg2][td=null,1]Texte 3[/td][/tr]\n[tr=bg1][td=null,1]Texte 4[/td][/tr]\n[tr=bg2][td=null,1]Texte 5[/td][/tr]\n[tr=bg1][td=null,1]Texte 6[/td][/tr][/tbody][/table]',
		'TABLE17'	=> '[size=130]Titre de la table[/size]\n[table=15,null][thead][tr=textleft][th=100,null]Titre[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][/tr]\n[tr=bg1][td=null,1]Texte 2[/td][/tr]\n[tr=bg2][td=null,1]Texte 3[/td][/tr]\n[tr=bg1][td=null,1]Texte 4[/td][/tr]\n[tr=bg2][td=null,1]Texte 5[/td][/tr]\n[tr=bg1][td=null,1]Texte 6[/td][/tr]\n[tr=bg2][td=null,1]Texte 7[/td][/tr][/tbody][/table]',
		'TABLE18'	=> '[size=130]Titre de la table[/size]\n[table=15,null][thead][tr=textleft][th=100,null]Titre[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][/tr]\n[tr=bg1][td=null,1]Texte 2[/td][/tr]\n[tr=bg2][td=null,1]Texte 3[/td][/tr]\n[tr=bg1][td=null,1]Texte 4[/td][/tr]\n[tr=bg2][td=null,1]Texte 5[/td][/tr]\n[tr=bg1][td=null,1]Texte 6[/td][/tr]\n[tr=bg2][td=null,1]Texte 7[/td][/tr]\n[tr=bg1][td=null,1]Texte 8[/td][/tr][/tbody][/table]',
		'TABLE19'	=> '[size=130]Titre de la table[/size]\n[table=15,null][thead][tr=textleft][th=100,null]Titre[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][/tr]\n[tr=bg1][td=null,1]Texte 2[/td][/tr]\n[tr=bg2][td=null,1]Texte 3[/td][/tr]\n[tr=bg1][td=null,1]Texte 4[/td][/tr]\n[tr=bg2][td=null,1]Texte 5[/td][/tr]\n[tr=bg1][td=null,1]Texte 6[/td][/tr]\n[tr=bg2][td=null,1]Texte 7[/td][/tr]\n[tr=bg1][td=null,1]Texte 8[/td][/tr]\n[tr=bg2][td=null,1]Texte 9[/td][/tr][/tbody][/table]',
		'TABLE110'	=> '[size=130]Titre de la table[/size]\n[table=15,null][thead][tr=textleft][th=100,null]Titre[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][/tr]\n[tr=bg1][td=null,1]Texte 2[/td][/tr]\n[tr=bg2][td=null,1]Texte 3[/td][/tr]\n[tr=bg1][td=null,1]Texte 4[/td][/tr]\n[tr=bg2][td=null,1]Texte 5[/td][/tr]\n[tr=bg1][td=null,1]Texte 6[/td][/tr]\n[tr=bg2][td=null,1]Texte 7[/td][/tr]\n[tr=bg1][td=null,1]Texte 8[/td][/tr]\n[tr=bg2][td=null,1]Texte 9[/td][/tr]\n[tr=bg1][td=null,1]Texte 10[/td][/tr][/tbody][/table]',
/**
* Column 2
*/
		'TABLE21'	=> '[size=130]Titre de la table[/size]\n[table=30,null][thead][tr=textleft][th=50,null]Titre 1[/th][th=50,null]Titre 2[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][td=null,1]Texte 2[/td][/tr][/tbody][/table]',
		'TABLE22'	=> '[size=130]Titre de la table[/size]\n[table=30,null][thead][tr=textleft][th=50,null]Titre 1[/th][th=50,null]Titre 2[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][/tr][/tbody][/table]',
		'TABLE23'	=> '[size=130]Titre de la table[/size]\n[table=30,null][thead][tr=textleft][th=50,null]Titre 1[/th][th=50,null]Titre 2[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][/tr][/tbody][/table]',
		'TABLE24'	=> '[size=130]Titre de la table[/size]\n[table=30,null][thead][tr=textleft][th=50,null]Titre 1[/th][th=50,null]Titre 2[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][/tr][/tbody][/table]',
		'TABLE25'	=> '[size=130]Titre de la table[/size]\n[table=30,null][thead][tr=textleft][th=50,null]Titre 1[/th][th=50,null]Titre 2[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][/tr][/tbody][/table]',
		'TABLE26'	=> '[size=130]Titre de la table[/size]\n[table=30,null][thead][tr=textleft][th=50,null]Titre 1[/th][th=50,null]Titre 2[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][/tr][/tbody][/table]',
		'TABLE27'	=> '[size=130]Titre de la table[/size]\n[table=30,null][thead][tr=textleft][th=50,null]Titre 1[/th][th=50,null]Titre 2[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][/tr][/tbody][/table]',
		'TABLE28'	=> '[size=130]Titre de la table[/size]\n[table=30,null][thead][tr=textleft][th=50,null]Titre 1[/th][th=50,null]Titre 2[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][/tr][/tbody][/table]',
		'TABLE29'	=> '[size=130]Titre de la table[/size]\n[table=30,null][thead][tr=textleft][th=50,null]Titre 1[/th][th=50,null]Titre 2[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][/tr]\n[tr=bg2][td=null,1]Texte 19[/td][td=null,1]Texte 29[/td][/tr][/tbody][/table]',
		'TABLE210'	=> '[size=130]Titre de la table[/size]\n[table=30,null][thead][tr=textleft][th=50,null]Titre 1[/th][th=50,null]Titre 2[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][/tr]\n[tr=bg2][td=null,1]Texte 19[/td][td=null,1]Texte 29[/td][/tr]\n[tr=bg1][td=null,1]Texte 110[/td][td=null,1]Texte 210[/td][/tr][/tbody][/table]',
/**
* Column 3
*/
		'TABLE31'	=> '[size=130]Titre de la table[/size]\n[table=45,null][thead][tr=textleft][th=33,null]Titre 1[/th][th=33,null]Titre 2[/th][th=34,null]Titre 3[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][td=null,1]Texte 2[/td][td=null,1]Texte 3[/td][/tr][/tbody][/table]',
		'TABLE32'	=> '[size=130]Titre de la table[/size]\n[table=45,null][thead][tr=textleft][th=33,null]Titre 1[/th][th=33,null]Titre 2[/th][th=34,null]Titre 3[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][/tr][/tbody][/table]',
		'TABLE33'	=> '[size=130]Titre de la table[/size]\n[table=45,null][thead][tr=textleft][th=33,null]Titre 1[/th][th=33,null]Titre 2[/th][th=34,null]Titre 3[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][/tr][/tbody][/table]',
		'TABLE34'	=> '[size=130]Titre de la table[/size]\n[table=45,null][thead][tr=textleft][th=33,null]Titre 1[/th][th=33,null]Titre 2[/th][th=34,null]Titre 3[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][/tr][/tbody][/table]',
		'TABLE35'	=> '[size=130]Titre de la table[/size]\n[table=45,null][thead][tr=textleft][th=33,null]Titre 1[/th][th=33,null]Titre 2[/th][th=34,null]Titre 3[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][/tr][/tbody][/table]',
		'TABLE36'	=> '[size=130]Titre de la table[/size]\n[table=45,null][thead][tr=textleft][th=33,null]Titre 1[/th][th=33,null]Titre 2[/th][th=34,null]Titre 3[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][/tr][/tbody][/table]',
		'TABLE37'	=> '[size=130]Titre de la table[/size]\n[table=45,null][thead][tr=textleft][th=33,null]Titre 1[/th][th=33,null]Titre 2[/th][th=34,null]Titre 3[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][/tr][/tbody][/table]',
		'TABLE38'	=> '[size=130]Titre de la table[/size]\n[table=45,null][thead][tr=textleft][th=33,null]Titre 1[/th][th=33,null]Titre 2[/th][th=34,null]Titre 3[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][/tr][/tbody][/table]',
		'TABLE39'	=> '[size=130]Titre de la table[/size]\n[table=45,null][thead][tr=textleft][th=33,null]Titre 1[/th][th=33,null]Titre 2[/th][th=34,null]Titre 3[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][/tr]\n[tr=bg2][td=null,1]Texte 19[/td][td=null,1]Texte 29[/td][td=null,1]Texte 39[/td][/tr][/tbody][/table]',
		'TABLE310'	=> '[size=130]Titre de la table[/size]\n[table=45,null][thead][tr=textleft][th=33,null]Titre 1[/th][th=33,null]Titre 2[/th][th=34,null]Titre 3[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][/tr]\n[tr=bg2][td=null,1]Texte 19[/td][td=null,1]Texte 29[/td][td=null,1]Texte 39[/td][/tr]\n[tr=bg1][td=null,1]Texte 110[/td][td=null,1]Texte 210[/td][td=null,1]Texte 310[/td][/tr][/tbody][/table]',
/**
* Column 4
*/
		'TABLE41'	=> '[size=130]Titre de la table[/size]\n[table=60,null][thead][tr=textleft][th=25,null]Titre 1[/th][th=25,null]Titre 2[/th][th=25,null]Titre 3[/th][th=25,null]Titre 4[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][td=null,1]Texte 2[/td][td=null,1]Texte 3[/td][td=null,1]Texte 4[/td][/tr][/tbody][/table]',
		'TABLE42'	=> '[size=130]Titre de la table[/size]\n[table=60,null][thead][tr=textleft][th=25,null]Titre 1[/th][th=25,null]Titre 2[/th][th=25,null]Titre 3[/th][th=25,null]Titre 4[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][/tr][/tbody][/table]',
		'TABLE43'	=> '[size=130]Titre de la table[/size]\n[table=60,null][thead][tr=textleft][th=25,null]Titre 1[/th][th=25,null]Titre 2[/th][th=25,null]Titre 3[/th][th=25,null]Titre 4[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][/tr][/tbody][/table]',
		'TABLE44'	=> '[size=130]Titre de la table[/size]\n[table=60,null][thead][tr=textleft][th=25,null]Titre 1[/th][th=25,null]Titre 2[/th][th=25,null]Titre 3[/th][th=25,null]Titre 4[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][/tr][/tbody][/table]',
		'TABLE45'	=> '[size=130]Titre de la table[/size]\n[table=60,null][thead][tr=textleft][th=25,null]Titre 1[/th][th=25,null]Titre 2[/th][th=25,null]Titre 3[/th][th=25,null]Titre 4[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][/tr][/tbody][/table]',
		'TABLE46'	=> '[size=130]Titre de la table[/size]\n[table=60,null][thead][tr=textleft][th=25,null]Titre 1[/th][th=25,null]Titre 2[/th][th=25,null]Titre 3[/th][th=25,null]Titre 4[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][/tr][/tbody][/table]',
		'TABLE47'	=> '[size=130]Titre de la table[/size]\n[table=60,null][thead][tr=textleft][th=25,null]Titre 1[/th][th=25,null]Titre 2[/th][th=25,null]Titre 3[/th][th=25,null]Titre 4[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][/tr][/tbody][/table]',
		'TABLE48'	=> '[size=130]Titre de la table[/size]\n[table=60,null][thead][tr=textleft][th=25,null]Titre 1[/th][th=25,null]Titre 2[/th][th=25,null]Titre 3[/th][th=25,null]Titre 4[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][td=null,1]Texte 48[/td][/tr][/tbody][/table]',
		'TABLE49'	=> '[size=130]Titre de la table[/size]\n[table=60,null][thead][tr=textleft][th=25,null]Titre 1[/th][th=25,null]Titre 2[/th][th=25,null]Titre 3[/th][th=25,null]Titre 4[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][td=null,1]Texte 48[/td][/tr]\n[tr=bg2][td=null,1]Texte 19[/td][td=null,1]Texte 29[/td][td=null,1]Texte 39[/td][td=null,1]Texte 49[/td][/tr][/tbody][/table]',
		'TABLE410'	=> '[size=130]Titre de la table[/size]\n[table=60,null][thead][tr=textleft][th=25,null]Titre 1[/th][th=25,null]Titre 2[/th][th=25,null]Titre 3[/th][th=25,null]Titre 4[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][td=null,1]Texte 48[/td][/tr]\n[tr=bg2][td=null,1]Texte 19[/td][td=null,1]Texte 29[/td][td=null,1]Texte 39[/td][td=null,1]Texte 49[/td][/tr]\n[tr=bg1][td=null,1]Texte 110[/td][td=null,1]Texte 210[/td][td=null,1]Texte 310[/td][td=null,1]Texte 410[/td][/tr][/tbody][/table]',
/**
* Column 5
*/
		'TABLE51'	=> '[size=130]Titre de la table[/size]\n[table=75,null][thead][tr=textleft][th=20,null]Titre 1[/th][th=20,null]Titre 2[/th][th=20,null]Titre 3[/th][th=20,null]Titre 4[/th][th=20,null]Titre 5[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][td=null,1]Texte 2[/td][td=null,1]Texte 3[/td][td=null,1]Texte 4[/td][td=null,1]Texte 5[/td][/tr][/tbody][/table]',
		'TABLE52'	=> '[size=130]Titre de la table[/size]\n[table=75,null][thead][tr=textleft][th=20,null]Titre 1[/th][th=20,null]Titre 2[/th][th=20,null]Titre 3[/th][th=20,null]Titre 4[/th][th=20,null]Titre 5[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][/tr][/tbody][/table]',
		'TABLE53'	=> '[size=130]Titre de la table[/size]\n[table=75,null][thead][tr=textleft][th=20,null]Titre 1[/th][th=20,null]Titre 2[/th][th=20,null]Titre 3[/th][th=20,null]Titre 4[/th][th=20,null]Titre 5[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][/tr][/tbody][/table]',
		'TABLE54'	=> '[size=130]Titre de la table[/size]\n[table=75,null][thead][tr=textleft][th=20,null]Titre 1[/th][th=20,null]Titre 2[/th][th=20,null]Titre 3[/th][th=20,null]Titre 4[/th][th=20,null]Titre 5[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][/tr][/tbody][/table]',
		'TABLE55'	=> '[size=130]Titre de la table[/size]\n[table=75,null][thead][tr=textleft][th=20,null]Titre 1[/th][th=20,null]Titre 2[/th][th=20,null]Titre 3[/th][th=20,null]Titre 4[/th][th=20,null]Titre 5[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][/tr][/tbody][/table]',
		'TABLE56'	=> '[size=130]Titre de la table[/size]\n[table=75,null][thead][tr=textleft][th=20,null]Titre 1[/th][th=20,null]Titre 2[/th][th=20,null]Titre 3[/th][th=20,null]Titre 4[/th][th=20,null]Titre 5[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][td=null,1]Texte 56[/td][/tr][/tbody][/table]',
		'TABLE57'	=> '[size=130]Titre de la table[/size]\n[table=75,null][thead][tr=textleft][th=20,null]Titre 1[/th][th=20,null]Titre 2[/th][th=20,null]Titre 3[/th][th=20,null]Titre 4[/th][th=20,null]Titre 5[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][td=null,1]Texte 56[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][td=null,1]Texte 57[/td][/tr][/tbody][/table]',
		'TABLE58'	=> '[size=130]Titre de la table[/size]\n[table=75,null][thead][tr=textleft][th=20,null]Titre 1[/th][th=20,null]Titre 2[/th][th=20,null]Titre 3[/th][th=20,null]Titre 4[/th][th=20,null]Titre 5[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][td=null,1]Texte 56[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][td=null,1]Texte 57[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][td=null,1]Texte 48[/td][td=null,1]Texte 58[/td][/tr][/tbody][/table]',
		'TABLE59'	=> '[size=130]Titre de la table[/size]\n[table=75,null][thead][tr=textleft][th=20,null]Titre 1[/th][th=20,null]Titre 2[/th][th=20,null]Titre 3[/th][th=20,null]Titre 4[/th][th=20,null]Titre 5[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][td=null,1]Texte 56[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][td=null,1]Texte 57[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][td=null,1]Texte 48[/td][td=null,1]Texte 58[/td][/tr]\n[tr=bg2][td=null,1]Texte 19[/td][td=null,1]Texte 29[/td][td=null,1]Texte 39[/td][td=null,1]Texte 49[/td][td=null,1]Texte 59[/td][/tr][/tbody][/table]',
		'TABLE510'	=> '[size=130]Titre de la table[/size]\n[table=75,null][thead][tr=textleft][th=20,null]Titre 1[/th][th=20,null]Titre 2[/th][th=20,null]Titre 3[/th][th=20,null]Titre 4[/th][th=20,null]Titre 5[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][td=null,1]Texte 56[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][td=null,1]Texte 57[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][td=null,1]Texte 48[/td][td=null,1]Texte 58[/td][/tr]\n[tr=bg2][td=null,1]Texte 19[/td][td=null,1]Texte 29[/td][td=null,1]Texte 39[/td][td=null,1]Texte 49[/td][td=null,1]Texte 59[/td][/tr]\n[tr=bg1][td=null,1]Texte 110[/td][td=null,1]Texte 210[/td][td=null,1]Texte 310[/td][td=null,1]Texte 410[/td][td=null,1]Texte 510[/td][/tr][/tbody][/table]',
/**
* Column 6
*/
		'TABLE61'	=> '[size=130]Titre de la table[/size]\n[table=90,null][thead][tr=textleft][th=17,null]Titre 1[/th][th=16,null]Titre 2[/th][th=17,null]Titre 3[/th][th=16,null]Titre 4[/th][th=17,null]Titre 5[/th][th=16,null]Titre 6[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 1[/td][td=null,1]Texte 2[/td][td=null,1]Texte 3[/td][td=null,1]Texte 4[/td][td=null,1]Texte 5[/td][td=null,1]Texte 6[/td][/tr][/tbody][/table]',
		'TABLE62'	=> '[size=130]Titre de la table[/size]\n[table=90,null][thead][tr=textleft][th=17,null]Titre 1[/th][th=16,null]Titre 2[/th][th=17,null]Titre 3[/th][th=16,null]Titre 4[/th][th=17,null]Titre 5[/th][th=16,null]Titre 6[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][td=null,1]Texte 61[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][td=null,1]Texte 62[/td][/tr][/tbody][/table]',
		'TABLE63'	=> '[size=130]Titre de la table[/size]\n[table=90,null][thead][tr=textleft][th=17,null]Titre 1[/th][th=16,null]Titre 2[/th][th=17,null]Titre 3[/th][th=16,null]Titre 4[/th][th=17,null]Titre 5[/th][th=16,null]Titre 6[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][td=null,1]Texte 61[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][td=null,1]Texte 62[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][td=null,1]Texte 63[/td][/tr][/tbody][/table]',
		'TABLE64'	=> '[size=130]Titre de la table[/size]\n[table=90,null][thead][tr=textleft][th=17,null]Titre 1[/th][th=16,null]Titre 2[/th][th=17,null]Titre 3[/th][th=16,null]Titre 4[/th][th=17,null]Titre 5[/th][th=16,null]Titre 6[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][td=null,1]Texte 61[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][td=null,1]Texte 62[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][td=null,1]Texte 63[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][td=null,1]Texte 64[/td][/tr][/tbody][/table]',
		'TABLE65'	=> '[size=130]Titre de la table[/size]\n[table=90,null][thead][tr=textleft][th=17,null]Titre 1[/th][th=16,null]Titre 2[/th][th=17,null]Titre 3[/th][th=16,null]Titre 4[/th][th=17,null]Titre 5[/th][th=16,null]Titre 6[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][td=null,1]Texte 61[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][td=null,1]Texte 62[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][td=null,1]Texte 63[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][td=null,1]Texte 64[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][td=null,1]Texte 65[/td][/tr][/tbody][/table]',
		'TABLE66'	=> '[size=130]Titre de la table[/size]\n[table=90,null][thead][tr=textleft][th=17,null]Titre 1[/th][th=16,null]Titre 2[/th][th=17,null]Titre 3[/th][th=16,null]Titre 4[/th][th=17,null]Titre 5[/th][th=16,null]Titre 6[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][td=null,1]Texte 61[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][td=null,1]Texte 62[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][td=null,1]Texte 63[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][td=null,1]Texte 64[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][td=null,1]Texte 65[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][td=null,1]Texte 56[/td][td=null,1]Texte 66[/td][/tr][/tbody][/table]',
		'TABLE67'	=> '[size=130]Titre de la table[/size]\n[table=90,null][thead][tr=textleft][th=17,null]Titre 1[/th][th=16,null]Titre 2[/th][th=17,null]Titre 3[/th][th=16,null]Titre 4[/th][th=17,null]Titre 5[/th][th=16,null]Titre 6[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][td=null,1]Texte 61[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][td=null,1]Texte 62[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][td=null,1]Texte 63[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][td=null,1]Texte 64[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][td=null,1]Texte 65[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][td=null,1]Texte 56[/td][td=null,1]Texte 66[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][td=null,1]Texte 57[/td][td=null,1]Texte 67[/td][/tr][/tbody][/table]',
		'TABLE68'	=> '[size=130]Titre de la table[/size]\n[table=90,null][thead][tr=textleft][th=17,null]Titre 1[/th][th=16,null]Titre 2[/th][th=17,null]Titre 3[/th][th=16,null]Titre 4[/th][th=17,null]Titre 5[/th][th=16,null]Titre 6[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][td=null,1]Texte 61[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][td=null,1]Texte 62[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][td=null,1]Texte 63[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][td=null,1]Texte 64[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][td=null,1]Texte 65[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][td=null,1]Texte 56[/td][td=null,1]Texte 66[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][td=null,1]Texte 57[/td][td=null,1]Texte 67[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][td=null,1]Texte 48[/td][td=null,1]Texte 58[/td][td=null,1]Texte 68[/td][/tr][/tbody][/table]',
		'TABLE69'	=> '[size=130]Titre de la table[/size]\n[table=90,null][thead][tr=textleft][th=17,null]Titre 1[/th][th=16,null]Titre 2[/th][th=17,null]Titre 3[/th][th=16,null]Titre 4[/th][th=17,null]Titre 5[/th][th=16,null]Titre 6[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][td=null,1]Texte 61[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][td=null,1]Texte 62[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][td=null,1]Texte 63[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][td=null,1]Texte 64[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][td=null,1]Texte 65[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][td=null,1]Texte 56[/td][td=null,1]Texte 66[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][td=null,1]Texte 57[/td][td=null,1]Texte 67[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][td=null,1]Texte 48[/td][td=null,1]Texte 58[/td][td=null,1]Texte 68[/td][/tr]\n[tr=bg2][td=null,1]Texte 19[/td][td=null,1]Texte 29[/td][td=null,1]Texte 39[/td][td=null,1]Texte 49[/td][td=null,1]Texte 59[/td][td=null,1]Texte 69[/td][/tr][/tbody][/table]',
		'TABLE610'	=> '[size=130]Titre de la table[/size]\n[table=90,null][thead][tr=textleft][th=17,null]Titre 1[/th][th=16,null]Titre 2[/th][th=17,null]Titre 3[/th][th=16,null]Titre 4[/th][th=17,null]Titre 5[/th][th=16,null]Titre 6[/th][/tr][/thead]\n[tbody][tr=bg2][td=null,1]Texte 11[/td][td=null,1]Texte 21[/td][td=null,1]Texte 31[/td][td=null,1]Texte 41[/td][td=null,1]Texte 51[/td][td=null,1]Texte 61[/td][/tr]\n[tr=bg1][td=null,1]Texte 12[/td][td=null,1]Texte 22[/td][td=null,1]Texte 32[/td][td=null,1]Texte 42[/td][td=null,1]Texte 52[/td][td=null,1]Texte 62[/td][/tr]\n[tr=bg2][td=null,1]Texte 13[/td][td=null,1]Texte 23[/td][td=null,1]Texte 33[/td][td=null,1]Texte 43[/td][td=null,1]Texte 53[/td][td=null,1]Texte 63[/td][/tr]\n[tr=bg1][td=null,1]Texte 14[/td][td=null,1]Texte 24[/td][td=null,1]Texte 34[/td][td=null,1]Texte 44[/td][td=null,1]Texte 54[/td][td=null,1]Texte 64[/td][/tr]\n[tr=bg2][td=null,1]Texte 15[/td][td=null,1]Texte 25[/td][td=null,1]Texte 35[/td][td=null,1]Texte 45[/td][td=null,1]Texte 55[/td][td=null,1]Texte 65[/td][/tr]\n[tr=bg1][td=null,1]Texte 16[/td][td=null,1]Texte 26[/td][td=null,1]Texte 36[/td][td=null,1]Texte 46[/td][td=null,1]Texte 56[/td][td=null,1]Texte 66[/td][/tr]\n[tr=bg2][td=null,1]Texte 17[/td][td=null,1]Texte 27[/td][td=null,1]Texte 37[/td][td=null,1]Texte 47[/td][td=null,1]Texte 57[/td][td=null,1]Texte 67[/td][/tr]\n[tr=bg1][td=null,1]Texte 18[/td][td=null,1]Texte 28[/td][td=null,1]Texte 38[/td][td=null,1]Texte 48[/td][td=null,1]Texte 58[/td][td=null,1]Texte 68[/td][/tr]\n[tr=bg2][td=null,1]Texte 19[/td][td=null,1]Texte 29[/td][td=null,1]Texte 39[/td][td=null,1]Texte 49[/td][td=null,1]Texte 59[/td][td=null,1]Texte 69[/td][/tr]\n[tr=bg1][td=null,1]Texte 110[/td][td=null,1]Texte 210[/td][td=null,1]Texte 310[/td][td=null,1]Texte 410[/td][td=null,1]Texte 510[/td][td=null,1]Texte 610[/td][/tr][/tbody][/table]',
	)
);
